module.exports = {
  segnalazioni: [],
  clienti: [
    {
      id: "cli_demo_1",
      codice: "CLI-SIDEIS-001",
      azienda: "Studio Luce Milano S.r.l.",
      tipo: "azienda",
      stato: "lead",
      categoria: "Lighting designer",
      area: "Lombardia",
      sottocategoria: "Progettazione architetturale",
      sottosettore: "Retail e hospitality",
      agente: "Marco Ferri",
      listino: "Demo 2026",
      fonte: "Demo CRM",
      dataNascita: "2016-03-14",
      piva: "03456010961",
      cf: "03456010961",
      nome: "Elena Vismara",
      email: "e.vismara@studioluce.it",
      telefono: "+39 02 440011",
      website: "www.studioluce-milano.it",
      pec: "studioluce@pecdemo.it",
      sdi: "SLD0011",
      sedeLegale: "Via Tortona 18, Milano",
      indirizzo: "Via Tortona 18, Milano",
      paese: "Italia",
      provincia: "MI",
      iban: "IT60X054281110100000000101",
      valore: 14500,
      sconto1: 0,
      sconto2: 0,
      sconto3: 0,
      terminiPagamento: "bonifico_30",
      note: "Cliente demo per showroom e retail."
    },
    {
      id: "cli_demo_2",
      codice: "CLI-SIDEIS-002",
      azienda: "Delta Impianti S.p.A.",
      tipo: "azienda",
      stato: "contattato",
      categoria: "Installatore",
      area: "Veneto",
      sottocategoria: "Contractor elettrico",
      sottosettore: "Industriale",
      agente: "Marco Ferri",
      listino: "Demo 2026",
      fonte: "Referral",
      dataNascita: "2008-09-02",
      piva: "04211030271",
      cf: "04211030271",
      nome: "Andrea Zanon",
      email: "a.zanon@deltaimpianti.it",
      telefono: "+39 049 771122",
      website: "www.deltaimpianti.it",
      pec: "deltaimpianti@pecdemo.it",
      sdi: "DLP0022",
      sedeLegale: "Via dell'Artigianato 42, Padova",
      indirizzo: "Via dell'Artigianato 42, Padova",
      paese: "Italia",
      provincia: "PD",
      iban: "IT60X054281110100000000102",
      valore: 22000,
      sconto1: 3,
      sconto2: 0,
      sconto3: 0,
      terminiPagamento: "bonifico_60",
      note: "Cliente demo per commesse impiantistiche."
    },
    {
      id: "cli_demo_3",
      codice: "CLI-SIDEIS-003",
      azienda: "Architettura Viva Roma",
      tipo: "lead",
      stato: "offerta",
      categoria: "Studio tecnico",
      area: "Lazio",
      sottocategoria: "Architettura",
      sottosettore: "Outdoor",
      agente: "Giulia Serra",
      listino: "Demo 2026",
      fonte: "Fiera",
      dataNascita: "2019-01-10",
      piva: "15678041004",
      cf: "15678041004",
      nome: "Sofia De Luca",
      email: "s.deluca@architetturaviva.it",
      telefono: "+39 06 889900",
      website: "www.architetturaviva.it",
      pec: "architetturaviva@pecdemo.it",
      sdi: "ARV0033",
      sedeLegale: "Via Flaminia 210, Roma",
      indirizzo: "Via Flaminia 210, Roma",
      paese: "Italia",
      provincia: "RM",
      iban: "IT60X054281110100000000103",
      valore: 9800,
      sconto1: 0,
      sconto2: 0,
      sconto3: 0,
      terminiPagamento: "vista_fattura",
      note: "Lead demo per progetti architetturali."
    }
  ],
  preventivi: [],
  preventiviAcquisto: [],
  ordiniVendita: [],
  ddtVendita: [],
  fornitori: [
    {
      id: "forn_casagrande",
      nome: "Casagrande",
      piva: "IT10000000001",
      cf: "IT10000000001",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale Casagrande",
      email: "info@casagrande.it",
      telefono: "+39 02 700000",
      pec: "casagrande@pecdemo.it",
      sdi: "SD00001",
      indirizzo: "Via Demo 10, Milano",
      sedeLegale: "Via Demo 10, Milano",
      iban: "IT60X054281110100000000001",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: Casagrande. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_ispa",
      nome: "ISPA",
      piva: "IT10000000002",
      cf: "IT10000000002",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale ISPA",
      email: "info@ispa.it",
      telefono: "+39 02 700137",
      pec: "ispa@pecdemo.it",
      sdi: "SD00002",
      indirizzo: "Via Demo 11, Milano",
      sedeLegale: "Via Demo 11, Milano",
      iban: "IT60X054281110100000000002",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: ISPA. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_entity",
      nome: "Entity",
      piva: "IT10000000003",
      cf: "IT10000000003",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale Entity",
      email: "info@entity.it",
      telefono: "+39 02 700274",
      pec: "entity@pecdemo.it",
      sdi: "SD00003",
      indirizzo: "Via Demo 12, Milano",
      sedeLegale: "Via Demo 12, Milano",
      iban: "IT60X054281110100000000003",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: Entity. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_gore",
      nome: "Gore",
      piva: "IT10000000004",
      cf: "IT10000000004",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale Gore",
      email: "info@gore.it",
      telefono: "+39 02 700411",
      pec: "gore@pecdemo.it",
      sdi: "SD00004",
      indirizzo: "Via Demo 13, Milano",
      sedeLegale: "Via Demo 13, Milano",
      iban: "IT60X054281110100000000004",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: Gore. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_mascherpa-cecchi",
      nome: "Mascherpa / Cecchi",
      piva: "IT10000000005",
      cf: "IT10000000005",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale Mascherpa / Cecchi",
      email: "info@mascherpacecchi.it",
      telefono: "+39 02 700548",
      pec: "mascherpacecchi@pecdemo.it",
      sdi: "SD00005",
      indirizzo: "Via Demo 14, Milano",
      sedeLegale: "Via Demo 14, Milano",
      iban: "IT60X054281110100000000005",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: DOW CORNIG. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_emc-colosio",
      nome: "EMC Colosio",
      piva: "IT10000000006",
      cf: "IT10000000006",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale EMC Colosio",
      email: "info@emccolosio.it",
      telefono: "+39 02 700685",
      pec: "emccolosio@pecdemo.it",
      sdi: "SD00006",
      indirizzo: "Via Demo 15, Milano",
      sedeLegale: "Via Demo 15, Milano",
      iban: "IT60X054281110100000000006",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: vari. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_fornitore-da-definire",
      nome: "Fornitore da definire",
      piva: "IT10000000007",
      cf: "IT10000000007",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale Fornitore da definire",
      email: "info@fornitoredadefinir.it",
      telefono: "+39 02 700822",
      pec: "fornitoredadefinire@pecdemo.it",
      sdi: "SD00007",
      indirizzo: "Via Demo 16, Milano",
      sedeLegale: "Via Demo 16, Milano",
      iban: "IT60X054281110100000000007",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Componenti senza fornitore esplicito nella BOM."
    },
    {
      id: "forn_elektrozubehor",
      nome: "Elektrozubehor",
      piva: "IT10000000008",
      cf: "IT10000000008",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale Elektrozubehor",
      email: "info@elektrozubehor.it",
      telefono: "+39 02 700959",
      pec: "elektrozubehor@pecdemo.it",
      sdi: "SD00008",
      indirizzo: "Via Demo 17, Milano",
      sedeLegale: "Via Demo 17, Milano",
      iban: "IT60X054281110100000000008",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: Elektrozubehor. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_mef",
      nome: "MEF",
      piva: "IT10000000009",
      cf: "IT10000000009",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale MEF",
      email: "info@mef.it",
      telefono: "+39 02 701096",
      pec: "mef@pecdemo.it",
      sdi: "SD00009",
      indirizzo: "Via Demo 18, Milano",
      sedeLegale: "Via Demo 18, Milano",
      iban: "IT60X054281110100000000009",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Costruttore prevalente: Cembre. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      id: "forn_bossard",
      nome: "Bossard",
      piva: "IT10000000010",
      cf: "IT10000000010",
      categoria: "componenti",
      statoQualifica: "approvato",
      referente: "Ufficio commerciale Bossard",
      email: "info@bossard.it",
      telefono: "+39 02 701233",
      pec: "bossard@pecdemo.it",
      sdi: "SD00010",
      indirizzo: "Via Demo 19, Milano",
      sedeLegale: "Via Demo 19, Milano",
      iban: "IT60X054281110100000000010",
      leadTime: 14,
      minimoOrdine: 100,
      terminiPagamento: "bonifico_60",
      note: "Fornitore minuterie e fissaggi emerso dalla distinta base."
    }
  ],
  ordiniAcquisto: [],
  ddtAcquisto: [],
  prodotti: [
    {
      id: "prod_sideis_one_cc",
      codice: "SIDEIS-ONE-CC",
      alias: "SIDEis ONE CC",
      nome: "Faretto SIDEis ONE CC",
      tipo: "kit",
      categoria: "Prodotti Finiti",
      sottocategoria: "Faretto tecnico",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 24.46,
      prezzoVendita: 62.37,
      sku: "SIDEIS-ONE-CC",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 12,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "SIDEIS-ONE-CC",
      peso: 0,
      volume: 0,
      produttore: "SIDEis",
      descrizioneTecnica: "Distinta base importata dal foglio SIDEis ONE CC. Versione demo pronta per preventivi e ordini."
    },
    {
      id: "prod_sideis_one_cv",
      codice: "SIDEIS-ONE-CV",
      alias: "SIDEis ONE CV",
      nome: "Faretto SIDEis ONE CV",
      tipo: "kit",
      categoria: "Prodotti Finiti",
      sottocategoria: "Faretto tecnico",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 31.3,
      prezzoVendita: 79.82,
      sku: "SIDEIS-ONE-CV",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 9,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "SIDEIS-ONE-CV",
      peso: 0,
      volume: 0,
      produttore: "SIDEis",
      descrizioneTecnica: "Distinta base importata dal foglio SIDEis ONE CV. Versione demo pronta per preventivi e ordini."
    },
    {
      id: "prod_001-05-23",
      codice: "001.05.23",
      alias: "001.05.23",
      nome: "LENTE ASIMMETRICA SIDEIS",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 4.52,
      prezzoVendita: 9.49,
      sku: "001.05.23",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Casagrande",
      descrizioneTecnica: "LENTE SIDEis S3 nuova 5' neutra senza cornice | NEUTRA | Approvvigionato da: SIDEis conto lavoro"
    },
    {
      id: "prod_10031",
      codice: "10031",
      alias: "10031",
      nome: "LENTE ASIMMETRICA SIDEIS",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 2.5,
      prezzoVendita: 5.25,
      sku: "10031",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Casagrande",
      descrizioneTecnica: "LENTE SIDEis S3 nuova 5' cornice tampografata | TAMPOGRAFATA | Approvvigionato da: SIDEis conto lavoro"
    },
    {
      id: "prod_002-01-22",
      codice: "002.01.22",
      alias: "002.01.22",
      nome: "SCOCCA BASE SIDEIS",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 3.76,
      prezzoVendita: 7.9,
      sku: "002.01.22",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "ISPA",
      descrizioneTecnica: "Componente meccanico da distinta base SIDEis ONE."
    },
    {
      id: "prod_003-01-22",
      codice: "003.01.22",
      alias: "003.01.22",
      nome: "DISSIPATORE SIDEIS",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 2.32,
      prezzoVendita: 4.87,
      sku: "003.01.22",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "ISPA",
      descrizioneTecnica: "Dissipatore meccanico da distinta base SIDEis ONE."
    },
    {
      id: "prod_auto-scheda-led-std-12-led",
      codice: "AUTO_SCHEDA_LED_STD_12_LED",
      alias: "xxxxx",
      nome: "scheda led STD 12 LED",
      tipo: "semplice",
      categoria: "Elettronica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 5.5,
      prezzoVendita: 12.93,
      sku: "AUTO_SCHEDA_LED_STD_12_LED",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Entity",
      descrizioneTecnica: "Scheda LED generica. Il codice in BOM era da definire."
    },
    {
      id: "prod_10217",
      codice: "10217",
      alias: "10217",
      nome: "scheda driver interna std",
      tipo: "semplice",
      categoria: "Elettronica",
      sottocategoria: "CV",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 6.84,
      prezzoVendita: 16.07,
      sku: "10217",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Entity",
      descrizioneTecnica: "Driver interno standard per versione CV."
    },
    {
      id: "prod_027-01-20",
      codice: "027.01.20",
      alias: "027.01.20",
      nome: "VALVOLA DI SFIATO (POLY VENT XS PMF200125)",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 1.8,
      prezzoVendita: 3.78,
      sku: "027.01.20",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "PMF200125",
      peso: 0,
      volume: 0,
      produttore: "Gore",
      descrizioneTecnica: "Valvola di sfiato Poly Vent XS PMF200125."
    },
    {
      id: "prod_10248",
      codice: "10248",
      alias: "10248",
      nome: "SILICONE",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.23,
      prezzoVendita: 0.48,
      sku: "10248",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "7091",
      peso: 0,
      volume: 0,
      produttore: "DOW CORNIG",
      descrizioneTecnica: "Dose di silicone per singolo prodotto."
    },
    {
      id: "prod_10250",
      codice: "10250",
      alias: "10250",
      nome: "PASTA TERMOCONDUTTIVA",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.05,
      prezzoVendita: 0.2,
      sku: "10250",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "HTC",
      peso: 0,
      volume: 0,
      produttore: "ELECTROLUBE",
      descrizioneTecnica: "Dose di pasta termoconduttiva per singolo prodotto."
    },
    {
      id: "prod_032-01-20",
      codice: "032.01.20",
      alias: "032.01.20",
      nome: "CAVO H05RN-F 2x0,75",
      tipo: "semplice",
      categoria: "Cablaggio",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.78,
      prezzoVendita: 1.83,
      sku: "032.01.20",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "vari",
      descrizioneTecnica: "Spezzone da 1,5 m come da distinta base."
    },
    {
      id: "prod_033-01-20",
      codice: "033.01.20",
      alias: "033.01.20",
      nome: "O-RING X VITI CHIUSURA",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.02,
      prezzoVendita: 0.17,
      sku: "033.01.20",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 240,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Fornitore da definire",
      descrizioneTecnica: "Minuteria di chiusura con qty 6 per prodotto."
    },
    {
      id: "prod_10036",
      codice: "10036",
      alias: "10036",
      nome: "passacavo M12x1,5",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.15,
      prezzoVendita: 0.32,
      sku: "10036",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "131390",
      peso: 0,
      volume: 0,
      produttore: "Elektrozubehor",
      descrizioneTecnica: "Alternativa al pressacavo a seconda del codice prodotto."
    },
    {
      id: "prod_024-01-20",
      codice: "024.01.20",
      alias: "024.01.20",
      nome: "pressacavo",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 1.54,
      prezzoVendita: 3.23,
      sku: "024.01.20",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "2900_M12N",
      peso: 0,
      volume: 0,
      produttore: "Cembre",
      descrizioneTecnica: "Alternativa al passacavo a seconda del codice prodotto."
    },
    {
      id: "prod_025-01-20",
      codice: "025.01.20",
      alias: "025.01.20",
      nome: "dado pressacavo",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.19,
      prezzoVendita: 0.4,
      sku: "025.01.20",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Cembre",
      descrizioneTecnica: "Accessorio del pressacavo da distinta base."
    },
    {
      id: "prod_012-01-20",
      codice: "012.01.20",
      alias: "012.01.20",
      nome: "VITE TRILOBATA M3 X 10 TORX A2 TESTA SVASATA",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.05,
      prezzoVendita: 0.2,
      sku: "012.01.20",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Bossard",
      descrizioneTecnica: "Minuteria da terzista per assemblaggio."
    },
    {
      id: "prod_10017",
      codice: "10017",
      alias: "10017",
      nome: "RONDELLA distanziale isolante 4,2x8 H5",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.05,
      prezzoVendita: 0.2,
      sku: "10017",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 80,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Bossard",
      descrizioneTecnica: "Rondella isolante con qty 2 per prodotto."
    },
    {
      id: "prod_10014",
      codice: "10014",
      alias: "10014",
      nome: "VITE TRILOBATA M4 X 10 TORX A2",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.03,
      prezzoVendita: 0.18,
      sku: "10014",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 240,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Bossard",
      descrizioneTecnica: "Vite trilobata M4x10 con qty 6 per prodotto."
    },
    {
      id: "prod_10277",
      codice: "10277",
      alias: "10277",
      nome: "VITE TRILOBATA M4 X 12 TORX A2",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.08,
      prezzoVendita: 0.23,
      sku: "10277",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 80,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Bossard",
      descrizioneTecnica: "Vite trilobata M4x12 con qty 2 per prodotto."
    },
    {
      id: "prod_10274",
      codice: "10274",
      alias: "10274",
      nome: "DADO FLANGIATO M6 A2",
      tipo: "semplice",
      categoria: "Meccanica",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.06,
      prezzoVendita: 0.21,
      sku: "10274",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 80,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Bossard",
      descrizioneTecnica: "Dado flangiato M6 A2 con qty 2 per prodotto."
    },
    {
      id: "prod_10278",
      codice: "10278",
      alias: "10278",
      nome: "IMBALLO",
      tipo: "semplice",
      categoria: "Imballo",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.07,
      prezzoVendita: 0.22,
      sku: "10278",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Fornitore da definire",
      descrizioneTecnica: "Quota imballo riferita al singolo prodotto."
    },
    {
      id: "prod_10009",
      codice: "10009",
      alias: "10009",
      nome: "VASSOIO contenitore 8 PZ",
      tipo: "semplice",
      categoria: "Imballo",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.19,
      prezzoVendita: 0.4,
      sku: "10009",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Fornitore da definire",
      descrizioneTecnica: "Vassoio contenitore con quota unitaria per singolo prodotto."
    },
    {
      id: "prod_auto-etichetta-prodotto-sx",
      codice: "AUTO_ETICHETTA_PRODOTTO_SX",
      alias: "",
      nome: "ETICHETTA PRODOTTO SX",
      tipo: "semplice",
      categoria: "Imballo",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.07,
      prezzoVendita: 0.22,
      sku: "AUTO_ETICHETTA_PRODOTTO_SX",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Fornitore da definire",
      descrizioneTecnica: "Etichetta prodotto per demo SIDEis ONE."
    },
    {
      id: "prod_auto-etichetta-marchi-dx",
      codice: "AUTO_ETICHETTA_MARCHI_DX",
      alias: "",
      nome: "ETICHETTA MARCHI DX",
      tipo: "semplice",
      categoria: "Imballo",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.07,
      prezzoVendita: 0.22,
      sku: "AUTO_ETICHETTA_MARCHI_DX",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Fornitore da definire",
      descrizioneTecnica: "Etichetta marchi lato destro per demo SIDEis ONE."
    },
    {
      id: "prod_auto-etichetta-bandiera-cavo",
      codice: "AUTO_ETICHETTA_BANDIERA_CAVO",
      alias: "",
      nome: "ETICHETTA BANDIERA CAVO",
      tipo: "semplice",
      categoria: "Imballo",
      sottocategoria: "CC",
      gruppo: "SIDEis ONE",
      iva: "22",
      prezzoAcquisto: 0.14,
      prezzoVendita: 0.29,
      sku: "AUTO_ETICHETTA_BANDIERA_CAVO",
      unitaMisura: "pz",
      quantitaConfezione: 1,
      quantitaEsistente: 40,
      brand: "SIDEis",
      provvigione: 0,
      barcode: "",
      metel: "",
      magazzino: "si",
      codDocumento: "",
      peso: 0,
      volume: 0,
      produttore: "Fornitore da definire",
      descrizioneTecnica: "Etichetta bandiera cavo per demo SIDEis ONE."
    }
  ],
  distintaBase: [
    {
      id: "bom_1",
      prodotto: "prod_sideis_one_cc",
      componentiCsv: "001.05.23:1, 10031:1, 002.01.22:1, 003.01.22:1, AUTO_SCHEDA_LED_STD_12_LED:1, 027.01.20:1, 10248:1, 10250:1, 032.01.20:1, 033.01.20:6, 024.01.20:1, 025.01.20:1, 012.01.20:1, 10017:2, 10014:6, 10277:2, 10274:2, 10278:1, 10009:1, AUTO_ETICHETTA_PRODOTTO_SX:1, AUTO_ETICHETTA_MARCHI_DX:1, AUTO_ETICHETTA_BANDIERA_CAVO:1"
    },
    {
      id: "bom_2",
      prodotto: "prod_sideis_one_cv",
      componentiCsv: "001.05.23:1, 10031:1, 002.01.22:1, 003.01.22:1, AUTO_SCHEDA_LED_STD_12_LED:1, 10217:1, 027.01.20:1, 10248:1, 10250:1, 032.01.20:1, 033.01.20:6, 024.01.20:1, 025.01.20:1, 012.01.20:1, 10017:2, 10014:6, 10277:2, 10274:2, 10278:1, 10009:1, AUTO_ETICHETTA_PRODOTTO_SX:1, AUTO_ETICHETTA_MARCHI_DX:1, AUTO_ETICHETTA_BANDIERA_CAVO:1"
    }
  ],
  magazzino: [
    { id: "mag_1", prodotto: "prod_sideis_one_cc", quantita: 12, quantitaMinima: 4, valoreFIFO: 293.52, ubicazione: "ASSEMBLAGGIO-01" },
    { id: "mag_2", prodotto: "prod_sideis_one_cv", quantita: 9, quantitaMinima: 4, valoreFIFO: 281.7, ubicazione: "ASSEMBLAGGIO-02" },
    { id: "mag_3", prodotto: "prod_001-05-23", quantita: 40, quantitaMinima: 10, valoreFIFO: 180.8, ubicazione: "COMP-03" },
    { id: "mag_4", prodotto: "prod_10031", quantita: 40, quantitaMinima: 10, valoreFIFO: 100, ubicazione: "COMP-04" },
    { id: "mag_5", prodotto: "prod_002-01-22", quantita: 40, quantitaMinima: 10, valoreFIFO: 150.4, ubicazione: "COMP-05" },
    { id: "mag_6", prodotto: "prod_003-01-22", quantita: 40, quantitaMinima: 10, valoreFIFO: 92.8, ubicazione: "COMP-06" },
    { id: "mag_7", prodotto: "prod_auto-scheda-led-std-12-led", quantita: 40, quantitaMinima: 10, valoreFIFO: 220, ubicazione: "COMP-07" },
    { id: "mag_8", prodotto: "prod_10217", quantita: 40, quantitaMinima: 10, valoreFIFO: 273.6, ubicazione: "COMP-08" },
    { id: "mag_9", prodotto: "prod_027-01-20", quantita: 40, quantitaMinima: 10, valoreFIFO: 72, ubicazione: "COMP-09" },
    { id: "mag_10", prodotto: "prod_10248", quantita: 40, quantitaMinima: 10, valoreFIFO: 9.2, ubicazione: "COMP-10" },
    { id: "mag_11", prodotto: "prod_10250", quantita: 40, quantitaMinima: 10, valoreFIFO: 2, ubicazione: "COMP-11" },
    { id: "mag_12", prodotto: "prod_032-01-20", quantita: 40, quantitaMinima: 10, valoreFIFO: 31.2, ubicazione: "COMP-12" },
    { id: "mag_13", prodotto: "prod_033-01-20", quantita: 240, quantitaMinima: 20, valoreFIFO: 4.8, ubicazione: "COMP-13" },
    { id: "mag_14", prodotto: "prod_10036", quantita: 40, quantitaMinima: 10, valoreFIFO: 6, ubicazione: "COMP-14" },
    { id: "mag_15", prodotto: "prod_024-01-20", quantita: 40, quantitaMinima: 10, valoreFIFO: 61.6, ubicazione: "COMP-15" },
    { id: "mag_16", prodotto: "prod_025-01-20", quantita: 40, quantitaMinima: 10, valoreFIFO: 7.6, ubicazione: "COMP-16" },
    { id: "mag_17", prodotto: "prod_012-01-20", quantita: 40, quantitaMinima: 10, valoreFIFO: 2, ubicazione: "COMP-17" },
    { id: "mag_18", prodotto: "prod_10017", quantita: 80, quantitaMinima: 20, valoreFIFO: 4, ubicazione: "COMP-18" },
    { id: "mag_19", prodotto: "prod_10014", quantita: 240, quantitaMinima: 20, valoreFIFO: 7.2, ubicazione: "COMP-19" },
    { id: "mag_20", prodotto: "prod_10277", quantita: 80, quantitaMinima: 20, valoreFIFO: 6.4, ubicazione: "COMP-20" },
    { id: "mag_21", prodotto: "prod_10274", quantita: 80, quantitaMinima: 20, valoreFIFO: 4.8, ubicazione: "COMP-21" },
    { id: "mag_22", prodotto: "prod_10278", quantita: 40, quantitaMinima: 10, valoreFIFO: 2.8, ubicazione: "COMP-22" },
    { id: "mag_23", prodotto: "prod_10009", quantita: 40, quantitaMinima: 10, valoreFIFO: 7.6, ubicazione: "COMP-23" },
    { id: "mag_24", prodotto: "prod_auto-etichetta-prodotto-sx", quantita: 40, quantitaMinima: 10, valoreFIFO: 2.8, ubicazione: "COMP-24" },
    { id: "mag_25", prodotto: "prod_auto-etichetta-marchi-dx", quantita: 40, quantitaMinima: 10, valoreFIFO: 2.8, ubicazione: "COMP-25" },
    { id: "mag_26", prodotto: "prod_auto-etichetta-bandiera-cavo", quantita: 40, quantitaMinima: 10, valoreFIFO: 5.6, ubicazione: "COMP-26" }
  ]
};
