window.CRM_SEED_DATA = {
  "segnalazioni": [],
  "clienti": [
    {
      "id": "cli_sim_1",
      "codice": "CLI-2001",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1974-02-09",
      "piva": "03012204153",
      "cf": "CF69514867626480",
      "nome": "Giuseppe Rossi",
      "email": "info@giusepperossi.it",
      "telefono": "+39 3746266267",
      "indirizzo": "Via Roma 58, Roma",
      "paese": "Italia",
      "provincia": "RO"
    },
    {
      "id": "cli_sim_2",
      "codice": "CLI-2002",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1986-01-01",
      "piva": "09165695147",
      "cf": "CF95557387745651",
      "nome": "Luigi Bianchi",
      "email": "info@luigibianchi.it",
      "telefono": "+39 3999891387",
      "indirizzo": "Via Roma 88, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_3",
      "codice": "CLI-2003",
      "azienda": "Impianti Sicuri SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1988-04-05",
      "piva": "08949254147",
      "cf": "CF35763069226058",
      "nome": "Marco Bianchi",
      "email": "info@impiantisicurisrl.it",
      "telefono": "+39 3336713074",
      "indirizzo": "Via Roma 65, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_4",
      "codice": "CLI-2004",
      "azienda": "Arredo Ufficio SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1979-06-16",
      "piva": "07335898589",
      "cf": "CF47036837955161",
      "nome": "Antonio Rossi",
      "email": "info@arredoufficiospa.it",
      "telefono": "+39 3754353417",
      "indirizzo": "Via Roma 45, Napoli",
      "paese": "Italia",
      "provincia": "NA"
    },
    {
      "id": "cli_sim_5",
      "codice": "CLI-2005",
      "azienda": "Luce & Design SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1978-07-31",
      "piva": "06919290204",
      "cf": "CF58860680077470",
      "nome": "Luigi Ferrari",
      "email": "info@luce&designspa.it",
      "telefono": "+39 3914066169",
      "indirizzo": "Via Roma 55, Torino",
      "paese": "Italia",
      "provincia": "TO"
    },
    {
      "id": "cli_sim_6",
      "codice": "CLI-2006",
      "azienda": "Luce & Design SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1991-10-19",
      "piva": "05967775309",
      "cf": "CF91703398598196",
      "nome": "Luigi Rossi",
      "email": "info@luce&designspa.it",
      "telefono": "+39 3056248237",
      "indirizzo": "Via Roma 27, Napoli",
      "paese": "Italia",
      "provincia": "NA"
    },
    {
      "id": "cli_sim_7",
      "codice": "CLI-2007",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1976-01-08",
      "piva": "04159639661",
      "cf": "CF93312207169926",
      "nome": "Giovanni Rossi",
      "email": "info@giovannirossi.it",
      "telefono": "+39 3755341024",
      "indirizzo": "Via Roma 59, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_8",
      "codice": "CLI-2008",
      "azienda": "Global Services Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1993-04-13",
      "piva": "06517959426",
      "cf": "CF89150224166306",
      "nome": "Mario Ferrari",
      "email": "info@globalservicessnc.it",
      "telefono": "+39 3249177009",
      "indirizzo": "Via Roma 59, Torino",
      "paese": "Italia",
      "provincia": "TO"
    },
    {
      "id": "cli_sim_9",
      "codice": "CLI-2009",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1992-05-26",
      "piva": "03094905285",
      "cf": "CF75876376926537",
      "nome": "Giovanni Ferrari",
      "email": "info@giovanniferrari.it",
      "telefono": "+39 3582328806",
      "indirizzo": "Via Roma 64, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_10",
      "codice": "CLI-2010",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1983-04-07",
      "piva": "05635931143",
      "cf": "CF83114955745093",
      "nome": "Marco Esposito",
      "email": "info@marcoesposito.it",
      "telefono": "+39 3053924591",
      "indirizzo": "Via Roma 6, Roma",
      "paese": "Italia",
      "provincia": "RO"
    },
    {
      "id": "cli_sim_11",
      "codice": "CLI-2011",
      "azienda": "Luce & Design SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1975-04-05",
      "piva": "04574664589",
      "cf": "CF95268772600008",
      "nome": "Mario Russo",
      "email": "info@luce&designspa.it",
      "telefono": "+39 3038484408",
      "indirizzo": "Via Roma 42, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_12",
      "codice": "CLI-2012",
      "azienda": "Luce & Design SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1991-11-25",
      "piva": "02374661322",
      "cf": "CF27815025835331",
      "nome": "Marco Russo",
      "email": "info@luce&designspa.it",
      "telefono": "+39 3269058623",
      "indirizzo": "Via Roma 8, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_13",
      "codice": "CLI-2013",
      "azienda": "Impianti Sicuri SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1982-12-03",
      "piva": "01174478973",
      "cf": "CF97053438345862",
      "nome": "Luigi Esposito",
      "email": "info@impiantisicurisrl.it",
      "telefono": "+39 3515159778",
      "indirizzo": "Via Roma 68, Milano",
      "paese": "Italia",
      "provincia": "MI"
    },
    {
      "id": "cli_sim_14",
      "codice": "CLI-2014",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1984-11-04",
      "piva": "03806037619",
      "cf": "CF70509309772858",
      "nome": "Marco Bianchi",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3519603657",
      "indirizzo": "Via Roma 54, Milano",
      "paese": "Italia",
      "provincia": "MI"
    },
    {
      "id": "cli_sim_15",
      "codice": "CLI-2015",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1981-09-12",
      "piva": "04168718667",
      "cf": "CF69779889114158",
      "nome": "Luigi Esposito",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3754033349",
      "indirizzo": "Via Roma 46, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_16",
      "codice": "CLI-2016",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1983-07-03",
      "piva": "03268152244",
      "cf": "CF46063540848950",
      "nome": "Luigi Rossi",
      "email": "info@luigirossi.it",
      "telefono": "+39 3520562009",
      "indirizzo": "Via Roma 55, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_17",
      "codice": "CLI-2017",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1980-12-02",
      "piva": "09683694066",
      "cf": "CF90481832304810",
      "nome": "Antonio Russo",
      "email": "info@antoniorusso.it",
      "telefono": "+39 3929706214",
      "indirizzo": "Via Roma 48, Roma",
      "paese": "Italia",
      "provincia": "RO"
    },
    {
      "id": "cli_sim_18",
      "codice": "CLI-2018",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1981-03-06",
      "piva": "01493239167",
      "cf": "CF74952532795364",
      "nome": "Giuseppe Rossi",
      "email": "info@giusepperossi.it",
      "telefono": "+39 3598650596",
      "indirizzo": "Via Roma 70, Napoli",
      "paese": "Italia",
      "provincia": "NA"
    },
    {
      "id": "cli_sim_19",
      "codice": "CLI-2019",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1985-04-20",
      "piva": "02523187417",
      "cf": "CF39385304906524",
      "nome": "Giuseppe Esposito",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3328104754",
      "indirizzo": "Via Roma 77, Milano",
      "paese": "Italia",
      "provincia": "MI"
    },
    {
      "id": "cli_sim_20",
      "codice": "CLI-2020",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1995-07-05",
      "piva": "05988650639",
      "cf": "CF20827878308335",
      "nome": "Mario Bianchi",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3522112737",
      "indirizzo": "Via Roma 94, Roma",
      "paese": "Italia",
      "provincia": "RO"
    }
  ],
  "preventivi": [
    {
      "id": "prev_sim_1",
      "numero": "PRE-2026001",
      "cliente": "cli_sim_5",
      "data": "2026-05-08",
      "dataScadenza": "2026-06-07",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 2,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 159.64,
      "tasse": 35.120799999999996,
      "totale": 194.7608,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_2",
      "numero": "PRE-2026002",
      "cliente": "cli_sim_14",
      "data": "2026-06-24",
      "dataScadenza": "2026-07-24",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 374.21999999999997,
      "tasse": 82.32839999999999,
      "totale": 456.54839999999996,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_3",
      "numero": "PRE-2026003",
      "cliente": "cli_sim_3",
      "data": "2026-02-07",
      "dataScadenza": "2026-03-09",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 5,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 399.09999999999997,
      "tasse": 87.80199999999999,
      "totale": 486.90199999999993,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_4",
      "numero": "PRE-2026004",
      "cliente": "cli_sim_7",
      "data": "2026-01-09",
      "dataScadenza": "2026-02-08",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 10,
          "prezzoUnitario": 79.82,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 1172.4199999999998,
      "tasse": 257.9324,
      "totale": 1430.3523999999998,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_5",
      "numero": "PRE-2026005",
      "cliente": "cli_sim_10",
      "data": "2026-04-14",
      "dataScadenza": "2026-05-14",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 1,
          "prezzoUnitario": 79.82,
          "sconto": 5
        }
      ],
      "imponibile": 450.049,
      "tasse": 99.01078,
      "totale": 549.0597799999999,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_6",
      "numero": "PRE-2026006",
      "cliente": "cli_sim_14",
      "data": "2026-04-01",
      "dataScadenza": "2026-05-01",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 3,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 187.10999999999999,
      "tasse": 41.164199999999994,
      "totale": 228.27419999999998,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_7",
      "numero": "PRE-2026007",
      "cliente": "cli_sim_16",
      "data": "2026-03-25",
      "dataScadenza": "2026-04-24",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 3,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 613.68,
      "tasse": 135.00959999999998,
      "totale": 748.6895999999999,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_8",
      "numero": "PRE-2026008",
      "cliente": "cli_sim_5",
      "data": "2026-05-26",
      "dataScadenza": "2026-06-25",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_9",
      "numero": "PRE-2026009",
      "cliente": "cli_sim_2",
      "data": "2026-03-04",
      "dataScadenza": "2026-04-03",
      "stato": "inviato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto": 10
        }
      ],
      "imponibile": 505.19699999999995,
      "tasse": 111.14334,
      "totale": 616.34034,
      "note": "Preventivo di vendita."
    },
    {
      "id": "prev_sim_10",
      "numero": "PRE-2026010",
      "cliente": "cli_sim_18",
      "data": "2026-05-19",
      "dataScadenza": "2026-06-18",
      "stato": "bozza",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 7,
          "prezzoUnitario": 79.82,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 932.96,
      "tasse": 205.2512,
      "totale": 1138.2112,
      "note": "Preventivo di vendita."
    }
  ],
  "preventiviAcquisto": [
    {
      "id": "preva_sim_1",
      "numero": "PRA-2026001",
      "fornitore": "forn_ispa",
      "data": "2026-01-06",
      "dataScadenza": "2026-02-05",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_002-01-22",
          "descrizione": "SCOCCA BASE SIDEIS",
          "quantita": 35,
          "prezzoUnitario": 3.76,
          "sconto": 0
        }
      ],
      "imponibile": 131.6,
      "tasse": 28.951999999999998,
      "totale": 160.552,
      "note": "Preventivo fornitore."
    },
    {
      "id": "preva_sim_2",
      "numero": "PRA-2026002",
      "fornitore": "forn_casagrande",
      "data": "2026-05-13",
      "dataScadenza": "2026-06-12",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_024-01-20",
          "descrizione": "pressacavo",
          "quantita": 32,
          "prezzoUnitario": 1.54,
          "sconto": 0
        },
        {
          "prodotto": "prod_10250",
          "descrizione": "PASTA TERMOCONDUTTIVA",
          "quantita": 40,
          "prezzoUnitario": 0.05,
          "sconto": 0
        },
        {
          "prodotto": "prod_auto-etichetta-marchi-dx",
          "descrizione": "ETICHETTA MARCHI DX",
          "quantita": 36,
          "prezzoUnitario": 0.07,
          "sconto": 0
        }
      ],
      "imponibile": 53.800000000000004,
      "tasse": 11.836,
      "totale": 65.63600000000001,
      "note": "Preventivo fornitore."
    },
    {
      "id": "preva_sim_3",
      "numero": "PRA-2026003",
      "fornitore": "forn_gore",
      "data": "2026-01-10",
      "dataScadenza": "2026-02-09",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_032-01-20",
          "descrizione": "CAVO H05RN-F 2x0,75",
          "quantita": 19,
          "prezzoUnitario": 0.78,
          "sconto": 0
        },
        {
          "prodotto": "prod_auto-scheda-led-std-12-led",
          "descrizione": "scheda led STD 12 LED",
          "quantita": 28,
          "prezzoUnitario": 5.5,
          "sconto": 0
        }
      ],
      "imponibile": 168.82,
      "tasse": 37.1404,
      "totale": 205.9604,
      "note": "Preventivo fornitore."
    },
    {
      "id": "preva_sim_4",
      "numero": "PRA-2026004",
      "fornitore": "forn_fornitore-da-definire",
      "data": "2026-02-18",
      "dataScadenza": "2026-03-20",
      "stato": "bozza",
      "righe": [
        {
          "prodotto": "prod_auto-etichetta-bandiera-cavo",
          "descrizione": "ETICHETTA BANDIERA CAVO",
          "quantita": 7,
          "prezzoUnitario": 0.14,
          "sconto": 5
        },
        {
          "prodotto": "prod_auto-etichetta-marchi-dx",
          "descrizione": "ETICHETTA MARCHI DX",
          "quantita": 10,
          "prezzoUnitario": 0.07,
          "sconto": 0
        }
      ],
      "imponibile": 1.6310000000000002,
      "tasse": 0.35882000000000003,
      "totale": 1.9898200000000001,
      "note": "Preventivo fornitore."
    }
  ],
  "ordiniVendita": [
    {
      "id": "ordv_sim_1",
      "numero": "ORD-2026001",
      "cliente": "cli_sim_5",
      "data": "2026-05-15",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 2,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 159.64,
      "tasse": 35.120799999999996,
      "totale": 194.7608,
      "preventivoOrigine": "prev_sim_1",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_2",
      "numero": "ORD-2026002",
      "cliente": "cli_sim_14",
      "data": "2026-07-06",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 374.21999999999997,
      "tasse": 82.32839999999999,
      "totale": 456.54839999999996,
      "preventivoOrigine": "prev_sim_2",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_3",
      "numero": "ORD-2026003",
      "cliente": "cli_sim_3",
      "data": "2026-02-19",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 5,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 399.09999999999997,
      "tasse": 87.80199999999999,
      "totale": 486.90199999999993,
      "preventivoOrigine": "prev_sim_3",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_4",
      "numero": "ORD-2026004",
      "cliente": "cli_sim_7",
      "data": "2026-01-10",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 10,
          "prezzoUnitario": 79.82,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 1172.4199999999998,
      "tasse": 257.9324,
      "totale": 1430.3523999999998,
      "preventivoOrigine": "prev_sim_4",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_5",
      "numero": "ORD-2026005",
      "cliente": "cli_sim_10",
      "data": "2026-04-24",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 1,
          "prezzoUnitario": 79.82,
          "sconto": 5
        }
      ],
      "imponibile": 450.049,
      "tasse": 99.01078,
      "totale": 549.0597799999999,
      "preventivoOrigine": "prev_sim_5",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_6",
      "numero": "ORD-2026006",
      "cliente": "cli_sim_14",
      "data": "2026-04-04",
      "stato": "inlavorazione",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 3,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 187.10999999999999,
      "tasse": 41.164199999999994,
      "totale": 228.27419999999998,
      "preventivoOrigine": "prev_sim_6",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_7",
      "numero": "ORD-2026007",
      "cliente": "cli_sim_16",
      "data": "2026-03-26",
      "stato": "confermato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 3,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 613.68,
      "tasse": 135.00959999999998,
      "totale": 748.6895999999999,
      "preventivoOrigine": "prev_sim_7",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_8",
      "numero": "ORD-2026008",
      "cliente": "cli_sim_5",
      "data": "2026-05-30",
      "stato": "confermato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "preventivoOrigine": "prev_sim_8",
      "note": "Ordine da preventivo confermato."
    }
  ],
  "ddtVendita": [
    {
      "id": "ddtv_sim_1",
      "numero": "DDT-2026001",
      "cliente": "cli_sim_5",
      "data": "2026-05-18",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 2,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 159.64,
      "tasse": 35.120799999999996,
      "totale": 194.7608,
      "ordineOrigine": "ordv_sim_1",
      "vettore": "DHL",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_2",
      "numero": "DDT-2026002",
      "cliente": "cli_sim_14",
      "data": "2026-07-10",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 374.21999999999997,
      "tasse": 82.32839999999999,
      "totale": 456.54839999999996,
      "ordineOrigine": "ordv_sim_2",
      "vettore": "SDA",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_3",
      "numero": "DDT-2026003",
      "cliente": "cli_sim_3",
      "data": "2026-02-27",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 5,
          "prezzoUnitario": 79.82,
          "sconto": 0
        }
      ],
      "imponibile": 399.09999999999997,
      "tasse": 87.80199999999999,
      "totale": 486.90199999999993,
      "ordineOrigine": "ordv_sim_3",
      "vettore": "SDA",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_4",
      "numero": "DDT-2026004",
      "cliente": "cli_sim_7",
      "data": "2026-01-13",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 10,
          "prezzoUnitario": 79.82,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        }
      ],
      "imponibile": 1172.4199999999998,
      "tasse": 257.9324,
      "totale": 1430.3523999999998,
      "ordineOrigine": "ordv_sim_4",
      "vettore": "BRT",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_5",
      "numero": "DDT-2026005",
      "cliente": "cli_sim_10",
      "data": "2026-04-25",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 6,
          "prezzoUnitario": 62.37,
          "sconto": 0
        },
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 1,
          "prezzoUnitario": 79.82,
          "sconto": 5
        }
      ],
      "imponibile": 450.049,
      "tasse": 99.01078,
      "totale": 549.0597799999999,
      "ordineOrigine": "ordv_sim_5",
      "vettore": "BRT",
      "note": "DDT per spedizione merci."
    }
  ],
  "fornitori": [
    {
      "id": "forn_casagrande",
      "nome": "Casagrande",
      "piva": "IT10000000001",
      "cf": "IT10000000001",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Casagrande",
      "email": "info@casagrande.it",
      "telefono": "+39 02 700000",
      "pec": "casagrande@pecdemo.it",
      "sdi": "SD00001",
      "indirizzo": "Via Demo 10, Milano",
      "sedeLegale": "Via Demo 10, Milano",
      "iban": "IT60X054281110100000000001",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Casagrande. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_ispa",
      "nome": "ISPA",
      "piva": "IT10000000002",
      "cf": "IT10000000002",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale ISPA",
      "email": "info@ispa.it",
      "telefono": "+39 02 700137",
      "pec": "ispa@pecdemo.it",
      "sdi": "SD00002",
      "indirizzo": "Via Demo 11, Milano",
      "sedeLegale": "Via Demo 11, Milano",
      "iban": "IT60X054281110100000000002",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: ISPA. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_entity",
      "nome": "Entity",
      "piva": "IT10000000003",
      "cf": "IT10000000003",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Entity",
      "email": "info@entity.it",
      "telefono": "+39 02 700274",
      "pec": "entity@pecdemo.it",
      "sdi": "SD00003",
      "indirizzo": "Via Demo 12, Milano",
      "sedeLegale": "Via Demo 12, Milano",
      "iban": "IT60X054281110100000000003",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Entity. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_gore",
      "nome": "Gore",
      "piva": "IT10000000004",
      "cf": "IT10000000004",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Gore",
      "email": "info@gore.it",
      "telefono": "+39 02 700411",
      "pec": "gore@pecdemo.it",
      "sdi": "SD00004",
      "indirizzo": "Via Demo 13, Milano",
      "sedeLegale": "Via Demo 13, Milano",
      "iban": "IT60X054281110100000000004",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Gore. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_mascherpa-cecchi",
      "nome": "Mascherpa / Cecchi",
      "piva": "IT10000000005",
      "cf": "IT10000000005",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Mascherpa / Cecchi",
      "email": "info@mascherpacecchi.it",
      "telefono": "+39 02 700548",
      "pec": "mascherpacecchi@pecdemo.it",
      "sdi": "SD00005",
      "indirizzo": "Via Demo 14, Milano",
      "sedeLegale": "Via Demo 14, Milano",
      "iban": "IT60X054281110100000000005",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: DOW CORNIG. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_emc-colosio",
      "nome": "EMC Colosio",
      "piva": "IT10000000006",
      "cf": "IT10000000006",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale EMC Colosio",
      "email": "info@emccolosio.it",
      "telefono": "+39 02 700685",
      "pec": "emccolosio@pecdemo.it",
      "sdi": "SD00006",
      "indirizzo": "Via Demo 15, Milano",
      "sedeLegale": "Via Demo 15, Milano",
      "iban": "IT60X054281110100000000006",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: vari. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_fornitore-da-definire",
      "nome": "Fornitore da definire",
      "piva": "IT10000000007",
      "cf": "IT10000000007",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Fornitore da definire",
      "email": "info@fornitoredadefinir.it",
      "telefono": "+39 02 700822",
      "pec": "fornitoredadefinire@pecdemo.it",
      "sdi": "SD00007",
      "indirizzo": "Via Demo 16, Milano",
      "sedeLegale": "Via Demo 16, Milano",
      "iban": "IT60X054281110100000000007",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Componenti senza fornitore esplicito nella BOM."
    },
    {
      "id": "forn_elektrozubehor",
      "nome": "Elektrozubehor",
      "piva": "IT10000000008",
      "cf": "IT10000000008",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Elektrozubehor",
      "email": "info@elektrozubehor.it",
      "telefono": "+39 02 700959",
      "pec": "elektrozubehor@pecdemo.it",
      "sdi": "SD00008",
      "indirizzo": "Via Demo 17, Milano",
      "sedeLegale": "Via Demo 17, Milano",
      "iban": "IT60X054281110100000000008",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Elektrozubehor. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_mef",
      "nome": "MEF",
      "piva": "IT10000000009",
      "cf": "IT10000000009",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale MEF",
      "email": "info@mef.it",
      "telefono": "+39 02 701096",
      "pec": "mef@pecdemo.it",
      "sdi": "SD00009",
      "indirizzo": "Via Demo 18, Milano",
      "sedeLegale": "Via Demo 18, Milano",
      "iban": "IT60X054281110100000000009",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Cembre. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_bossard",
      "nome": "Bossard",
      "piva": "IT10000000010",
      "cf": "IT10000000010",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Bossard",
      "email": "info@bossard.it",
      "telefono": "+39 02 701233",
      "pec": "bossard@pecdemo.it",
      "sdi": "SD00010",
      "indirizzo": "Via Demo 19, Milano",
      "sedeLegale": "Via Demo 19, Milano",
      "iban": "IT60X054281110100000000010",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Fornitore minuterie e fissaggi emerso dalla distinta base."
    }
  ],
  "ordiniAcquisto": [
    {
      "id": "orda_sim_1",
      "numero": "OAC-2026001",
      "fornitore": "forn_ispa",
      "data": "2026-01-21",
      "stato": "ricevuto",
      "righe": [
        {
          "prodotto": "prod_002-01-22",
          "descrizione": "SCOCCA BASE SIDEIS",
          "quantita": 35,
          "prezzoUnitario": 3.76,
          "sconto": 0
        }
      ],
      "imponibile": 131.6,
      "tasse": 28.951999999999998,
      "totale": 160.552,
      "preventivoOrigine": "preva_sim_1",
      "note": "Ordine inviato a fornitore."
    },
    {
      "id": "orda_sim_2",
      "numero": "OAC-2026002",
      "fornitore": "forn_casagrande",
      "data": "2026-05-18",
      "stato": "ricevuto",
      "righe": [
        {
          "prodotto": "prod_024-01-20",
          "descrizione": "pressacavo",
          "quantita": 32,
          "prezzoUnitario": 1.54,
          "sconto": 0
        },
        {
          "prodotto": "prod_10250",
          "descrizione": "PASTA TERMOCONDUTTIVA",
          "quantita": 40,
          "prezzoUnitario": 0.05,
          "sconto": 0
        },
        {
          "prodotto": "prod_auto-etichetta-marchi-dx",
          "descrizione": "ETICHETTA MARCHI DX",
          "quantita": 36,
          "prezzoUnitario": 0.07,
          "sconto": 0
        }
      ],
      "imponibile": 53.800000000000004,
      "tasse": 11.836,
      "totale": 65.63600000000001,
      "preventivoOrigine": "preva_sim_2",
      "note": "Ordine inviato a fornitore."
    },
    {
      "id": "orda_sim_3",
      "numero": "OAC-2026003",
      "fornitore": "forn_gore",
      "data": "2026-01-18",
      "stato": "ricevuto",
      "righe": [
        {
          "prodotto": "prod_032-01-20",
          "descrizione": "CAVO H05RN-F 2x0,75",
          "quantita": 19,
          "prezzoUnitario": 0.78,
          "sconto": 0
        },
        {
          "prodotto": "prod_auto-scheda-led-std-12-led",
          "descrizione": "scheda led STD 12 LED",
          "quantita": 28,
          "prezzoUnitario": 5.5,
          "sconto": 0
        }
      ],
      "imponibile": 168.82,
      "tasse": 37.1404,
      "totale": 205.9604,
      "preventivoOrigine": "preva_sim_3",
      "note": "Ordine inviato a fornitore."
    }
  ],
  "ddtAcquisto": [
    {
      "id": "ddta_sim_1",
      "numero": "DDA-2026001",
      "fornitore": "forn_ispa",
      "data": "2026-01-25",
      "stato": "registrato",
      "righe": [
        {
          "prodotto": "prod_002-01-22",
          "descrizione": "SCOCCA BASE SIDEIS",
          "quantita": 35,
          "prezzoUnitario": 3.76,
          "sconto": 0
        }
      ],
      "imponibile": 131.6,
      "tasse": 28.951999999999998,
      "totale": 160.552,
      "ordineOrigine": "orda_sim_1",
      "vettore": "Mittente",
      "note": "Ricezione merce."
    },
    {
      "id": "ddta_sim_2",
      "numero": "DDA-2026002",
      "fornitore": "forn_casagrande",
      "data": "2026-05-22",
      "stato": "registrato",
      "righe": [
        {
          "prodotto": "prod_024-01-20",
          "descrizione": "pressacavo",
          "quantita": 32,
          "prezzoUnitario": 1.54,
          "sconto": 0
        },
        {
          "prodotto": "prod_10250",
          "descrizione": "PASTA TERMOCONDUTTIVA",
          "quantita": 40,
          "prezzoUnitario": 0.05,
          "sconto": 0
        },
        {
          "prodotto": "prod_auto-etichetta-marchi-dx",
          "descrizione": "ETICHETTA MARCHI DX",
          "quantita": 36,
          "prezzoUnitario": 0.07,
          "sconto": 0
        }
      ],
      "imponibile": 53.800000000000004,
      "tasse": 11.836,
      "totale": 65.63600000000001,
      "ordineOrigine": "orda_sim_2",
      "vettore": "Mittente",
      "note": "Ricezione merce."
    },
    {
      "id": "ddta_sim_3",
      "numero": "DDA-2026003",
      "fornitore": "forn_gore",
      "data": "2026-02-03",
      "stato": "registrato",
      "righe": [
        {
          "prodotto": "prod_032-01-20",
          "descrizione": "CAVO H05RN-F 2x0,75",
          "quantita": 19,
          "prezzoUnitario": 0.78,
          "sconto": 0
        },
        {
          "prodotto": "prod_auto-scheda-led-std-12-led",
          "descrizione": "scheda led STD 12 LED",
          "quantita": 28,
          "prezzoUnitario": 5.5,
          "sconto": 0
        }
      ],
      "imponibile": 168.82,
      "tasse": 37.1404,
      "totale": 205.9604,
      "ordineOrigine": "orda_sim_3",
      "vettore": "Mittente",
      "note": "Ricezione merce."
    }
  ],
  "prodotti": [
    {
      "id": "prod_sideis_one_cc",
      "codice": "SIDEIS-ONE-CC",
      "alias": "SIDEis ONE CC",
      "nome": "Faretto SIDEis ONE CC",
      "tipo": "kit",
      "categoria": "Prodotti Finiti",
      "sottocategoria": "Faretto tecnico",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 24.46,
      "prezzoVendita": 62.37,
      "sku": "SIDEIS-ONE-CC",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 12,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "SIDEIS-ONE-CC",
      "peso": 0,
      "volume": 0,
      "produttore": "SIDEis",
      "descrizioneTecnica": "Distinta base importata dal foglio SIDEis ONE CC. Versione demo pronta per preventivi e ordini."
    },
    {
      "id": "prod_sideis_one_cv",
      "codice": "SIDEIS-ONE-CV",
      "alias": "SIDEis ONE CV",
      "nome": "Faretto SIDEis ONE CV",
      "tipo": "kit",
      "categoria": "Prodotti Finiti",
      "sottocategoria": "Faretto tecnico",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 31.3,
      "prezzoVendita": 79.82,
      "sku": "SIDEIS-ONE-CV",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 9,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "SIDEIS-ONE-CV",
      "peso": 0,
      "volume": 0,
      "produttore": "SIDEis",
      "descrizioneTecnica": "Distinta base importata dal foglio SIDEis ONE CV. Versione demo pronta per preventivi e ordini."
    },
    {
      "id": "prod_001-05-23",
      "codice": "001.05.23",
      "alias": "001.05.23",
      "nome": "LENTE ASIMMETRICA SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 4.52,
      "prezzoVendita": 9.49,
      "sku": "001.05.23",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Casagrande",
      "descrizioneTecnica": "LENTE SIDEis S3 nuova 5' neutra senza cornice | NEUTRA | Approvvigionato da: SIDEis conto lavoro"
    },
    {
      "id": "prod_10031",
      "codice": "10031",
      "alias": "10031",
      "nome": "LENTE ASIMMETRICA SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 2.5,
      "prezzoVendita": 5.25,
      "sku": "10031",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Casagrande",
      "descrizioneTecnica": "LENTE SIDEis S3 nuova 5' cornice tampografata | TAMPOGRAFATA | Approvvigionato da: SIDEis conto lavoro"
    },
    {
      "id": "prod_002-01-22",
      "codice": "002.01.22",
      "alias": "002.01.22",
      "nome": "SCOCCA BASE SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 3.76,
      "prezzoVendita": 7.9,
      "sku": "002.01.22",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "ISPA",
      "descrizioneTecnica": "Componente meccanico da distinta base SIDEis ONE."
    },
    {
      "id": "prod_003-01-22",
      "codice": "003.01.22",
      "alias": "003.01.22",
      "nome": "DISSIPATORE SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 2.32,
      "prezzoVendita": 4.87,
      "sku": "003.01.22",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "ISPA",
      "descrizioneTecnica": "Dissipatore meccanico da distinta base SIDEis ONE."
    },
    {
      "id": "prod_auto-scheda-led-std-12-led",
      "codice": "AUTO_SCHEDA_LED_STD_12_LED",
      "alias": "xxxxx",
      "nome": "scheda led STD 12 LED",
      "tipo": "semplice",
      "categoria": "Elettronica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 5.5,
      "prezzoVendita": 12.93,
      "sku": "AUTO_SCHEDA_LED_STD_12_LED",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Entity",
      "descrizioneTecnica": "Scheda LED generica. Il codice in BOM era da definire."
    },
    {
      "id": "prod_10217",
      "codice": "10217",
      "alias": "10217",
      "nome": "scheda driver interna std",
      "tipo": "semplice",
      "categoria": "Elettronica",
      "sottocategoria": "CV",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 6.84,
      "prezzoVendita": 16.07,
      "sku": "10217",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Entity",
      "descrizioneTecnica": "Driver interno standard per versione CV."
    },
    {
      "id": "prod_027-01-20",
      "codice": "027.01.20",
      "alias": "027.01.20",
      "nome": "VALVOLA DI SFIATO (POLY VENT XS PMF200125)",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 1.8,
      "prezzoVendita": 3.78,
      "sku": "027.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "PMF200125",
      "peso": 0,
      "volume": 0,
      "produttore": "Gore",
      "descrizioneTecnica": "Valvola di sfiato Poly Vent XS PMF200125."
    },
    {
      "id": "prod_10248",
      "codice": "10248",
      "alias": "10248",
      "nome": "SILICONE",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.23,
      "prezzoVendita": 0.48,
      "sku": "10248",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "7091",
      "peso": 0,
      "volume": 0,
      "produttore": "DOW CORNIG",
      "descrizioneTecnica": "Dose di silicone per singolo prodotto."
    },
    {
      "id": "prod_10250",
      "codice": "10250",
      "alias": "10250",
      "nome": "PASTA TERMOCONDUTTIVA",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.05,
      "prezzoVendita": 0.2,
      "sku": "10250",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "HTC",
      "peso": 0,
      "volume": 0,
      "produttore": "ELECTROLUBE",
      "descrizioneTecnica": "Dose di pasta termoconduttiva per singolo prodotto."
    },
    {
      "id": "prod_032-01-20",
      "codice": "032.01.20",
      "alias": "032.01.20",
      "nome": "CAVO H05RN-F 2x0,75",
      "tipo": "semplice",
      "categoria": "Cablaggio",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.78,
      "prezzoVendita": 1.83,
      "sku": "032.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "vari",
      "descrizioneTecnica": "Spezzone da 1,5 m come da distinta base."
    },
    {
      "id": "prod_033-01-20",
      "codice": "033.01.20",
      "alias": "033.01.20",
      "nome": "O-RING X VITI CHIUSURA",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.02,
      "prezzoVendita": 0.17,
      "sku": "033.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 240,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Minuteria di chiusura con qty 6 per prodotto."
    },
    {
      "id": "prod_10036",
      "codice": "10036",
      "alias": "10036",
      "nome": "passacavo M12x1,5",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.15,
      "prezzoVendita": 0.32,
      "sku": "10036",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "131390",
      "peso": 0,
      "volume": 0,
      "produttore": "Elektrozubehor",
      "descrizioneTecnica": "Alternativa al pressacavo a seconda del codice prodotto."
    },
    {
      "id": "prod_024-01-20",
      "codice": "024.01.20",
      "alias": "024.01.20",
      "nome": "pressacavo",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 1.54,
      "prezzoVendita": 3.23,
      "sku": "024.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "2900_M12N",
      "peso": 0,
      "volume": 0,
      "produttore": "Cembre",
      "descrizioneTecnica": "Alternativa al passacavo a seconda del codice prodotto."
    },
    {
      "id": "prod_025-01-20",
      "codice": "025.01.20",
      "alias": "025.01.20",
      "nome": "dado pressacavo",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.19,
      "prezzoVendita": 0.4,
      "sku": "025.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Cembre",
      "descrizioneTecnica": "Accessorio del pressacavo da distinta base."
    },
    {
      "id": "prod_012-01-20",
      "codice": "012.01.20",
      "alias": "012.01.20",
      "nome": "VITE TRILOBATA M3 X 10 TORX A2 TESTA SVASATA",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.05,
      "prezzoVendita": 0.2,
      "sku": "012.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Minuteria da terzista per assemblaggio."
    },
    {
      "id": "prod_10017",
      "codice": "10017",
      "alias": "10017",
      "nome": "RONDELLA distanziale isolante 4,2x8 H5",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.05,
      "prezzoVendita": 0.2,
      "sku": "10017",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 80,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Rondella isolante con qty 2 per prodotto."
    },
    {
      "id": "prod_10014",
      "codice": "10014",
      "alias": "10014",
      "nome": "VITE TRILOBATA M4 X 10 TORX A2",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.03,
      "prezzoVendita": 0.18,
      "sku": "10014",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 240,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Vite trilobata M4x10 con qty 6 per prodotto."
    },
    {
      "id": "prod_10277",
      "codice": "10277",
      "alias": "10277",
      "nome": "VITE TRILOBATA M4 X 12 TORX A2",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.08,
      "prezzoVendita": 0.23,
      "sku": "10277",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 80,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Vite trilobata M4x12 con qty 2 per prodotto."
    },
    {
      "id": "prod_10274",
      "codice": "10274",
      "alias": "10274",
      "nome": "DADO FLANGIATO M6 A2",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.06,
      "prezzoVendita": 0.21,
      "sku": "10274",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 80,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Dado flangiato M6 A2 con qty 2 per prodotto."
    },
    {
      "id": "prod_10278",
      "codice": "10278",
      "alias": "10278",
      "nome": "IMBALLO",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.07,
      "prezzoVendita": 0.22,
      "sku": "10278",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Quota imballo riferita al singolo prodotto."
    },
    {
      "id": "prod_10009",
      "codice": "10009",
      "alias": "10009",
      "nome": "VASSOIO contenitore 8 PZ",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.19,
      "prezzoVendita": 0.4,
      "sku": "10009",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Vassoio contenitore con quota unitaria per singolo prodotto."
    },
    {
      "id": "prod_auto-etichetta-prodotto-sx",
      "codice": "AUTO_ETICHETTA_PRODOTTO_SX",
      "alias": "",
      "nome": "ETICHETTA PRODOTTO SX",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.07,
      "prezzoVendita": 0.22,
      "sku": "AUTO_ETICHETTA_PRODOTTO_SX",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Etichetta prodotto per demo SIDEis ONE."
    },
    {
      "id": "prod_auto-etichetta-marchi-dx",
      "codice": "AUTO_ETICHETTA_MARCHI_DX",
      "alias": "",
      "nome": "ETICHETTA MARCHI DX",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.07,
      "prezzoVendita": 0.22,
      "sku": "AUTO_ETICHETTA_MARCHI_DX",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Etichetta marchi lato destro per demo SIDEis ONE."
    },
    {
      "id": "prod_auto-etichetta-bandiera-cavo",
      "codice": "AUTO_ETICHETTA_BANDIERA_CAVO",
      "alias": "",
      "nome": "ETICHETTA BANDIERA CAVO",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.14,
      "prezzoVendita": 0.29,
      "sku": "AUTO_ETICHETTA_BANDIERA_CAVO",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Etichetta bandiera cavo per demo SIDEis ONE."
    }
  ],
  "distintaBase": [
    {
      "id": "bom_1",
      "prodotto": "prod_sideis_one_cc",
      "componentiCsv": "001.05.23:1, 10031:1, 002.01.22:1, 003.01.22:1, AUTO_SCHEDA_LED_STD_12_LED:1, 027.01.20:1, 10248:1, 10250:1, 032.01.20:1, 033.01.20:6, 024.01.20:1, 025.01.20:1, 012.01.20:1, 10017:2, 10014:6, 10277:2, 10274:2, 10278:1, 10009:1, AUTO_ETICHETTA_PRODOTTO_SX:1, AUTO_ETICHETTA_MARCHI_DX:1, AUTO_ETICHETTA_BANDIERA_CAVO:1"
    },
    {
      "id": "bom_2",
      "prodotto": "prod_sideis_one_cv",
      "componentiCsv": "001.05.23:1, 10031:1, 002.01.22:1, 003.01.22:1, AUTO_SCHEDA_LED_STD_12_LED:1, 10217:1, 027.01.20:1, 10248:1, 10250:1, 032.01.20:1, 033.01.20:6, 024.01.20:1, 025.01.20:1, 012.01.20:1, 10017:2, 10014:6, 10277:2, 10274:2, 10278:1, 10009:1, AUTO_ETICHETTA_PRODOTTO_SX:1, AUTO_ETICHETTA_MARCHI_DX:1, AUTO_ETICHETTA_BANDIERA_CAVO:1"
    }
  ],
  "magazzino": [
    {
      "id": "mag_1",
      "prodotto": "prod_sideis_one_cc",
      "quantita": 12,
      "quantitaMinima": 4,
      "valoreFIFO": 293.52,
      "ubicazione": "ASSEMBLAGGIO-01"
    },
    {
      "id": "mag_2",
      "prodotto": "prod_sideis_one_cv",
      "quantita": 9,
      "quantitaMinima": 4,
      "valoreFIFO": 281.7,
      "ubicazione": "ASSEMBLAGGIO-02"
    },
    {
      "id": "mag_3",
      "prodotto": "prod_001-05-23",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 180.8,
      "ubicazione": "COMP-03"
    },
    {
      "id": "mag_4",
      "prodotto": "prod_10031",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 100,
      "ubicazione": "COMP-04"
    },
    {
      "id": "mag_5",
      "prodotto": "prod_002-01-22",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 150.4,
      "ubicazione": "COMP-05"
    },
    {
      "id": "mag_6",
      "prodotto": "prod_003-01-22",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 92.8,
      "ubicazione": "COMP-06"
    },
    {
      "id": "mag_7",
      "prodotto": "prod_auto-scheda-led-std-12-led",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 220,
      "ubicazione": "COMP-07"
    },
    {
      "id": "mag_8",
      "prodotto": "prod_10217",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 273.6,
      "ubicazione": "COMP-08"
    },
    {
      "id": "mag_9",
      "prodotto": "prod_027-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 72,
      "ubicazione": "COMP-09"
    },
    {
      "id": "mag_10",
      "prodotto": "prod_10248",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 9.2,
      "ubicazione": "COMP-10"
    },
    {
      "id": "mag_11",
      "prodotto": "prod_10250",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2,
      "ubicazione": "COMP-11"
    },
    {
      "id": "mag_12",
      "prodotto": "prod_032-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 31.2,
      "ubicazione": "COMP-12"
    },
    {
      "id": "mag_13",
      "prodotto": "prod_033-01-20",
      "quantita": 240,
      "quantitaMinima": 20,
      "valoreFIFO": 4.8,
      "ubicazione": "COMP-13"
    },
    {
      "id": "mag_14",
      "prodotto": "prod_10036",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 6,
      "ubicazione": "COMP-14"
    },
    {
      "id": "mag_15",
      "prodotto": "prod_024-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 61.6,
      "ubicazione": "COMP-15"
    },
    {
      "id": "mag_16",
      "prodotto": "prod_025-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 7.6,
      "ubicazione": "COMP-16"
    },
    {
      "id": "mag_17",
      "prodotto": "prod_012-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2,
      "ubicazione": "COMP-17"
    },
    {
      "id": "mag_18",
      "prodotto": "prod_10017",
      "quantita": 80,
      "quantitaMinima": 20,
      "valoreFIFO": 4,
      "ubicazione": "COMP-18"
    },
    {
      "id": "mag_19",
      "prodotto": "prod_10014",
      "quantita": 240,
      "quantitaMinima": 20,
      "valoreFIFO": 7.2,
      "ubicazione": "COMP-19"
    },
    {
      "id": "mag_20",
      "prodotto": "prod_10277",
      "quantita": 80,
      "quantitaMinima": 20,
      "valoreFIFO": 6.4,
      "ubicazione": "COMP-20"
    },
    {
      "id": "mag_21",
      "prodotto": "prod_10274",
      "quantita": 80,
      "quantitaMinima": 20,
      "valoreFIFO": 4.8,
      "ubicazione": "COMP-21"
    },
    {
      "id": "mag_22",
      "prodotto": "prod_10278",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2.8,
      "ubicazione": "COMP-22"
    },
    {
      "id": "mag_23",
      "prodotto": "prod_10009",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 7.6,
      "ubicazione": "COMP-23"
    },
    {
      "id": "mag_24",
      "prodotto": "prod_auto-etichetta-prodotto-sx",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2.8,
      "ubicazione": "COMP-24"
    },
    {
      "id": "mag_25",
      "prodotto": "prod_auto-etichetta-marchi-dx",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2.8,
      "ubicazione": "COMP-25"
    },
    {
      "id": "mag_26",
      "prodotto": "prod_auto-etichetta-bandiera-cavo",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 5.6,
      "ubicazione": "COMP-26"
    }
  ]
};