window.CRM_SEED_DATA = {
  "segnalazioni": [],
  "clienti": [
    {
      "id": "cli_sim_1",
      "codice": "CLI-2001",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1980-08-29",
      "piva": "06240429049",
      "cf": "CF45824855978635",
      "nome": "Marco Rossi",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3057420968",
      "indirizzo": "Via Roma 92, Roma",
      "paese": "Italia",
      "provincia": "RO"
    },
    {
      "id": "cli_sim_2",
      "codice": "CLI-2002",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1988-02-21",
      "piva": "07707503540",
      "cf": "CF81635770817709",
      "nome": "Giuseppe Bianchi",
      "email": "info@giuseppebianchi.it",
      "telefono": "+39 3109484721",
      "indirizzo": "Via Roma 83, Napoli",
      "paese": "Italia",
      "provincia": "NA"
    },
    {
      "id": "cli_sim_3",
      "codice": "CLI-2003",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1992-08-30",
      "piva": "05554589743",
      "cf": "CF78382249461232",
      "nome": "Giuseppe Rossi",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3427499554",
      "indirizzo": "Via Roma 8, Roma",
      "paese": "Italia",
      "provincia": "RO"
    },
    {
      "id": "cli_sim_4",
      "codice": "CLI-2004",
      "azienda": "Luce & Design SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1989-07-20",
      "piva": "04950273929",
      "cf": "CF85355207449622",
      "nome": "Giovanni Rossi",
      "email": "info@luce&designspa.it",
      "telefono": "+39 3774983808",
      "indirizzo": "Via Roma 49, Torino",
      "paese": "Italia",
      "provincia": "TO"
    },
    {
      "id": "cli_sim_5",
      "codice": "CLI-2005",
      "azienda": "Global Services Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1991-10-22",
      "piva": "06807242371",
      "cf": "CF42447006323523",
      "nome": "Giuseppe Rossi",
      "email": "info@globalservicessnc.it",
      "telefono": "+39 3847625152",
      "indirizzo": "Via Roma 15, Milano",
      "paese": "Italia",
      "provincia": "MI"
    },
    {
      "id": "cli_sim_6",
      "codice": "CLI-2006",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1983-01-23",
      "piva": "06402154209",
      "cf": "CF87161893649357",
      "nome": "Giuseppe Russo",
      "email": "info@giusepperusso.it",
      "telefono": "+39 3547486759",
      "indirizzo": "Via Roma 70, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_7",
      "codice": "CLI-2007",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1980-10-04",
      "piva": "07700310933",
      "cf": "CF37296569623156",
      "nome": "Mario Ferrari",
      "email": "info@marioferrari.it",
      "telefono": "+39 3505783050",
      "indirizzo": "Via Roma 68, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_8",
      "codice": "CLI-2008",
      "azienda": "Arredo Ufficio SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1979-03-20",
      "piva": "03675832093",
      "cf": "CF11538161826295",
      "nome": "Antonio Esposito",
      "email": "info@arredoufficiospa.it",
      "telefono": "+39 3101037182",
      "indirizzo": "Via Roma 96, Milano",
      "paese": "Italia",
      "provincia": "MI"
    },
    {
      "id": "cli_sim_9",
      "codice": "CLI-2009",
      "azienda": "Tech Solutions SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1973-07-28",
      "piva": "06428755842",
      "cf": "CF32575380527904",
      "nome": "Luigi Bianchi",
      "email": "info@techsolutionssrl.it",
      "telefono": "+39 3073133681",
      "indirizzo": "Via Roma 46, Torino",
      "paese": "Italia",
      "provincia": "TO"
    },
    {
      "id": "cli_sim_10",
      "codice": "CLI-2010",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1972-11-22",
      "piva": "08797191205",
      "cf": "CF42750583298517",
      "nome": "Mario Rossi",
      "email": "info@mariorossi.it",
      "telefono": "+39 3925843766",
      "indirizzo": "Via Roma 20, Milano",
      "paese": "Italia",
      "provincia": "MI"
    },
    {
      "id": "cli_sim_11",
      "codice": "CLI-2011",
      "azienda": "Tech Solutions SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1983-01-28",
      "piva": "08676773623",
      "cf": "CF28116566769622",
      "nome": "Luigi Russo",
      "email": "info@techsolutionssrl.it",
      "telefono": "+39 3384273355",
      "indirizzo": "Via Roma 90, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_12",
      "codice": "CLI-2012",
      "azienda": "Tech Solutions SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1992-08-27",
      "piva": "03886830916",
      "cf": "CF97788545017778",
      "nome": "Marco Ferrari",
      "email": "info@techsolutionssrl.it",
      "telefono": "+39 3505482693",
      "indirizzo": "Via Roma 4, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_13",
      "codice": "CLI-2013",
      "azienda": "Arredo Ufficio SPA",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1990-12-12",
      "piva": "09573930004",
      "cf": "CF75568804444915",
      "nome": "Mario Ferrari",
      "email": "info@arredoufficiospa.it",
      "telefono": "+39 3554525943",
      "indirizzo": "Via Roma 67, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_14",
      "codice": "CLI-2014",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1992-08-16",
      "piva": "06497299380",
      "cf": "CF32121674270642",
      "nome": "Luigi Ferrari",
      "email": "info@luigiferrari.it",
      "telefono": "+39 3543175239",
      "indirizzo": "Via Roma 59, Roma",
      "paese": "Italia",
      "provincia": "RO"
    },
    {
      "id": "cli_sim_15",
      "codice": "CLI-2015",
      "azienda": "Impianti Sicuri SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1991-09-19",
      "piva": "05953304505",
      "cf": "CF86450987470354",
      "nome": "Antonio Esposito",
      "email": "info@impiantisicurisrl.it",
      "telefono": "+39 3292205705",
      "indirizzo": "Via Roma 26, Milano",
      "paese": "Italia",
      "provincia": "MI"
    },
    {
      "id": "cli_sim_16",
      "codice": "CLI-2016",
      "azienda": "Impianti Sicuri SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1985-01-27",
      "piva": "05336176090",
      "cf": "CF25849513801694",
      "nome": "Antonio Esposito",
      "email": "info@impiantisicurisrl.it",
      "telefono": "+39 3893063986",
      "indirizzo": "Via Roma 1, Genova",
      "paese": "Italia",
      "provincia": "GE"
    },
    {
      "id": "cli_sim_17",
      "codice": "CLI-2017",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1992-12-16",
      "piva": "06145871012",
      "cf": "CF75589556850368",
      "nome": "Antonio Rossi",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3722286053",
      "indirizzo": "Via Roma 20, Roma",
      "paese": "Italia",
      "provincia": "RO"
    },
    {
      "id": "cli_sim_18",
      "codice": "CLI-2018",
      "azienda": "Edilizia Moderna Snc",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1980-05-29",
      "piva": "09020073519",
      "cf": "CF54278657408109",
      "nome": "Luigi Romano",
      "email": "info@ediliziamodernasnc.it",
      "telefono": "+39 3976976321",
      "indirizzo": "Via Roma 4, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_19",
      "codice": "CLI-2019",
      "azienda": "Tech Solutions SRL",
      "tipo": "azienda",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1993-01-18",
      "piva": "02609346274",
      "cf": "CF31446931977155",
      "nome": "Marco Rossi",
      "email": "info@techsolutionssrl.it",
      "telefono": "+39 3587197724",
      "indirizzo": "Via Roma 90, Palermo",
      "paese": "Italia",
      "provincia": "PA"
    },
    {
      "id": "cli_sim_20",
      "codice": "CLI-2020",
      "azienda": "",
      "tipo": "privato",
      "stato": "attivo",
      "categoria": "Cliente",
      "agente": "Marco Ferri",
      "dataNascita": "1978-05-18",
      "piva": "06015428138",
      "cf": "CF50147741017406",
      "nome": "Marco Russo",
      "email": "info@marcorusso.it",
      "telefono": "+39 3386617392",
      "indirizzo": "Via Roma 89, Roma",
      "paese": "Italia",
      "provincia": "RO"
    }
  ],
  "preventivi": [
    {
      "id": "prev_sim_1",
      "numero": "PRE-2026001",
      "sezionale": "00",
      "titolo": "Fornitura faretti led",
      "cliente": "cli_sim_1",
      "azienda": "Edilizia Moderna Snc",
      "destinazione": "Magazzino Milano",
      "agente": "Giacomo",
      "condizioniPagamento": "bonifico_60",
      "porto": "franco",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-03-06",
      "dataScadenza": "2026-04-05",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 10,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 623.6999999999999,
      "tasse": 137.214,
      "totale": 760.9139999999999,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_2",
      "numero": "PRE-2026002",
      "sezionale": "00",
      "titolo": "Progetto illuminazione villa",
      "cliente": "cli_sim_8",
      "azienda": "Arredo Ufficio SPA",
      "destinazione": "Sede Cliente",
      "agente": "Marco Ferri",
      "condizioniPagamento": "riba_30_60",
      "porto": "franco",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-06-14",
      "dataScadenza": "2026-07-14",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 4,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 5,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_3",
      "numero": "PRE-2026003",
      "sezionale": "00",
      "titolo": "Sostituzione faretti esterni",
      "cliente": "cli_sim_15",
      "azienda": "Impianti Sicuri SRL",
      "destinazione": "Magazzino Milano",
      "agente": "Giacomo",
      "condizioniPagamento": "vista_fattura",
      "porto": "assegnato",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": true,
      "data": "2026-01-30",
      "dataScadenza": "2026-03-01",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_4",
      "numero": "PRE-2026004",
      "sezionale": "00",
      "titolo": "Fornitura faretti led",
      "cliente": "cli_sim_15",
      "azienda": "Impianti Sicuri SRL",
      "destinazione": "Cantiere Roma",
      "agente": "Roberto Pagliai",
      "condizioniPagamento": "riba_30_60",
      "porto": "assegnato",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-02-27",
      "dataScadenza": "2026-03-29",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 3,
          "prezzoUnitario": 62.37,
          "sconto1": 5,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 177.75449999999998,
      "tasse": 39.10599,
      "totale": 216.86048999999997,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_5",
      "numero": "PRE-2026005",
      "sezionale": "00",
      "titolo": "Luci per showroom",
      "cliente": "cli_sim_3",
      "azienda": "Edilizia Moderna Snc",
      "destinazione": "Sede Cliente",
      "agente": "Roberto Pagliai",
      "condizioniPagamento": "riba_30_60",
      "porto": "franco",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-04-01",
      "dataScadenza": "2026-05-01",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 10,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 623.6999999999999,
      "tasse": 137.214,
      "totale": 760.9139999999999,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_6",
      "numero": "PRE-2026006",
      "sezionale": "00",
      "titolo": "Fornitura faretti led",
      "cliente": "cli_sim_17",
      "azienda": "Edilizia Moderna Snc",
      "destinazione": "Magazzino Milano",
      "agente": "Roberto Pagliai",
      "condizioniPagamento": "vista_fattura",
      "porto": "assegnato",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-06-05",
      "dataScadenza": "2026-07-05",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 5,
          "prezzoUnitario": 79.82,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 3,
          "prezzoUnitario": 62.37,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 558.1434999999999,
      "tasse": 122.79156999999998,
      "totale": 680.9350699999999,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_7",
      "numero": "PRE-2026007",
      "sezionale": "00",
      "titolo": "Fornitura faretti led",
      "cliente": "cli_sim_11",
      "azienda": "Tech Solutions SRL",
      "destinazione": "Sede Cliente",
      "agente": "Giacomo",
      "condizioniPagamento": "bonifico_60",
      "porto": "franco",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-01-19",
      "dataScadenza": "2026-02-18",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 6,
          "prezzoUnitario": 79.82,
          "sconto1": 5,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 932.1044999999999,
      "tasse": 205.06298999999999,
      "totale": 1137.1674899999998,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_8",
      "numero": "PRE-2026008",
      "sezionale": "00",
      "titolo": "Luci per showroom",
      "cliente": "cli_sim_5",
      "azienda": "Global Services Snc",
      "destinazione": "",
      "agente": "Roberto Pagliai",
      "condizioniPagamento": "vista_fattura",
      "porto": "assegnato",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": true,
      "data": "2026-05-21",
      "dataScadenza": "2026-06-20",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 2,
          "prezzoUnitario": 79.82,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 159.64,
      "tasse": 35.120799999999996,
      "totale": 194.7608,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_9",
      "numero": "PRE-2026009",
      "sezionale": "00",
      "titolo": "Illuminazione uffici",
      "cliente": "cli_sim_6",
      "azienda": "DA DEFINIRE",
      "destinazione": "Magazzino Milano",
      "agente": "Giacomo",
      "condizioniPagamento": "bonifico_30",
      "porto": "franco",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-03-01",
      "dataScadenza": "2026-03-31",
      "stato": "bozza",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 10,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 1,
          "prezzoUnitario": 79.82,
          "sconto1": 5,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 699.5289999999999,
      "tasse": 153.89637999999997,
      "totale": 853.4253799999998,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    },
    {
      "id": "prev_sim_10",
      "numero": "PRE-2026010",
      "sezionale": "00",
      "titolo": "Progetto illuminazione villa",
      "cliente": "cli_sim_20",
      "azienda": "DA DEFINIRE",
      "destinazione": "Magazzino Milano",
      "agente": "Marco Ferri",
      "condizioniPagamento": "bonifico_60",
      "porto": "assegnato",
      "listino": "Standard",
      "ivaGenerale": 22,
      "mostraImponibile": true,
      "mostraIva": true,
      "mostraScontiRiga": true,
      "mostraScontiTotali": true,
      "esportato": false,
      "data": "2026-03-23",
      "dataScadenza": "2026-04-22",
      "stato": "bozza",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 2,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 6,
          "prezzoUnitario": 79.82,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 531.8219999999999,
      "tasse": 117.00083999999998,
      "totale": 648.8228399999998,
      "note": "Preventivo di vendita.",
      "noteInterne": "Verificare disponibilità componenti prima dell'invio.",
      "testoFondo": "Grazie per la collaborazione. Validità offerta: 30gg."
    }
  ],
  "preventiviAcquisto": [
    {
      "id": "preva_sim_1",
      "numero": "PRA-2026001",
      "fornitore": "forn_fornitore-da-definire",
      "data": "2026-05-30",
      "dataScadenza": "2026-06-29",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_auto-etichetta-prodotto-sx",
          "descrizione": "ETICHETTA PRODOTTO SX",
          "quantita": 42,
          "prezzoUnitario": 0.07,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 0.14,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 2.9400000000000004,
      "tasse": 0.6468,
      "totale": 3.5868,
      "note": "Preventivo fornitore."
    },
    {
      "id": "preva_sim_2",
      "numero": "PRA-2026002",
      "fornitore": "forn_mascherpa-cecchi",
      "data": "2026-04-10",
      "dataScadenza": "2026-05-10",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_auto-scheda-led-std-12-led",
          "descrizione": "scheda led STD 12 LED",
          "quantita": 48,
          "prezzoUnitario": 5.5,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 11,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10009",
          "descrizione": "VASSOIO contenitore 8 PZ",
          "quantita": 1,
          "prezzoUnitario": 0.19,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 0.38,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10277",
          "descrizione": "VITE TRILOBATA M4 X 12 TORX A2",
          "quantita": 29,
          "prezzoUnitario": 0.08,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 0.16,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 266.4815,
      "tasse": 58.62593,
      "totale": 325.10742999999997,
      "note": "Preventivo fornitore."
    },
    {
      "id": "preva_sim_3",
      "numero": "PRA-2026003",
      "fornitore": "forn_mef",
      "data": "2026-05-09",
      "dataScadenza": "2026-06-08",
      "stato": "accettato",
      "righe": [
        {
          "prodotto": "prod_003-01-22",
          "descrizione": "DISSIPATORE SIDEIS",
          "quantita": 43,
          "prezzoUnitario": 2.32,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 4.64,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 99.75999999999999,
      "tasse": 21.9472,
      "totale": 121.70719999999999,
      "note": "Preventivo fornitore."
    },
    {
      "id": "preva_sim_4",
      "numero": "PRA-2026004",
      "fornitore": "forn_gore",
      "data": "2026-01-10",
      "dataScadenza": "2026-02-09",
      "stato": "bozza",
      "righe": [
        {
          "prodotto": "prod_027-01-20",
          "descrizione": "VALVOLA DI SFIATO (POLY VENT XS PMF200125)",
          "quantita": 26,
          "prezzoUnitario": 1.8,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 3.6,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_auto-scheda-led-std-12-led",
          "descrizione": "scheda led STD 12 LED",
          "quantita": 41,
          "prezzoUnitario": 5.5,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 11,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10031",
          "descrizione": "LENTE ASIMMETRICA SIDEIS",
          "quantita": 36,
          "prezzoUnitario": 2.5,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 5,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10036",
          "descrizione": "passacavo M12x1,5",
          "quantita": 27,
          "prezzoUnitario": 0.15,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 0.3,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 366.35,
      "tasse": 80.59700000000001,
      "totale": 446.947,
      "note": "Preventivo fornitore."
    }
  ],
  "ordiniVendita": [
    {
      "id": "ordv_sim_1",
      "numero": "ORD-2026001",
      "cliente": "cli_sim_1",
      "data": "2026-03-09",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 10,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 623.6999999999999,
      "tasse": 137.214,
      "totale": 760.9139999999999,
      "preventivoOrigine": "prev_sim_1",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_2",
      "numero": "ORD-2026002",
      "cliente": "cli_sim_8",
      "data": "2026-06-23",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 4,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 5,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "preventivoOrigine": "prev_sim_2",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_3",
      "numero": "ORD-2026003",
      "cliente": "cli_sim_15",
      "data": "2026-02-05",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "preventivoOrigine": "prev_sim_3",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_4",
      "numero": "ORD-2026004",
      "cliente": "cli_sim_15",
      "data": "2026-03-03",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 3,
          "prezzoUnitario": 62.37,
          "sconto1": 5,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 177.75449999999998,
      "tasse": 39.10599,
      "totale": 216.86048999999997,
      "preventivoOrigine": "prev_sim_4",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_5",
      "numero": "ORD-2026005",
      "cliente": "cli_sim_3",
      "data": "2026-04-13",
      "stato": "spedito",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 10,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 623.6999999999999,
      "tasse": 137.214,
      "totale": 760.9139999999999,
      "preventivoOrigine": "prev_sim_5",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_6",
      "numero": "ORD-2026006",
      "cliente": "cli_sim_17",
      "data": "2026-06-18",
      "stato": "inlavorazione",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 5,
          "prezzoUnitario": 79.82,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 3,
          "prezzoUnitario": 62.37,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 558.1434999999999,
      "tasse": 122.79156999999998,
      "totale": 680.9350699999999,
      "preventivoOrigine": "prev_sim_6",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_7",
      "numero": "ORD-2026007",
      "cliente": "cli_sim_11",
      "data": "2026-01-25",
      "stato": "inlavorazione",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 6,
          "prezzoUnitario": 79.82,
          "sconto1": 5,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 932.1044999999999,
      "tasse": 205.06298999999999,
      "totale": 1137.1674899999998,
      "preventivoOrigine": "prev_sim_7",
      "note": "Ordine da preventivo confermato."
    },
    {
      "id": "ordv_sim_8",
      "numero": "ORD-2026008",
      "cliente": "cli_sim_5",
      "data": "2026-06-02",
      "stato": "inlavorazione",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cv",
          "descrizione": "Faretto SIDEis ONE CV",
          "quantita": 2,
          "prezzoUnitario": 79.82,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 62.6,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 159.64,
      "tasse": 35.120799999999996,
      "totale": 194.7608,
      "preventivoOrigine": "prev_sim_8",
      "note": "Ordine da preventivo confermato."
    }
  ],
  "ddtVendita": [
    {
      "id": "ddtv_sim_1",
      "numero": "DDT-2026001",
      "cliente": "cli_sim_1",
      "data": "2026-03-13",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 10,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 623.6999999999999,
      "tasse": 137.214,
      "totale": 760.9139999999999,
      "ordineOrigine": "ordv_sim_1",
      "vettore": "BRT",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_2",
      "numero": "DDT-2026002",
      "cliente": "cli_sim_8",
      "data": "2026-06-27",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 4,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 5,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "ordineOrigine": "ordv_sim_2",
      "vettore": "BRT",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_3",
      "numero": "DDT-2026003",
      "cliente": "cli_sim_15",
      "data": "2026-02-10",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 9,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 561.3299999999999,
      "tasse": 123.49259999999998,
      "totale": 684.8225999999999,
      "ordineOrigine": "ordv_sim_3",
      "vettore": "SDA",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_4",
      "numero": "DDT-2026004",
      "cliente": "cli_sim_15",
      "data": "2026-03-11",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 3,
          "prezzoUnitario": 62.37,
          "sconto1": 5,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 177.75449999999998,
      "tasse": 39.10599,
      "totale": 216.86048999999997,
      "ordineOrigine": "ordv_sim_4",
      "vettore": "BRT",
      "note": "DDT per spedizione merci."
    },
    {
      "id": "ddtv_sim_5",
      "numero": "DDT-2026005",
      "cliente": "cli_sim_3",
      "data": "2026-04-16",
      "stato": "fatturato",
      "righe": [
        {
          "prodotto": "prod_sideis_one_cc",
          "descrizione": "Faretto SIDEis ONE CC",
          "quantita": 10,
          "prezzoUnitario": 62.37,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Illuminazione",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 48.92,
          "quantitaConfezione": 1,
          "tipologia": "prodotto",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 623.6999999999999,
      "tasse": 137.214,
      "totale": 760.9139999999999,
      "ordineOrigine": "ordv_sim_5",
      "vettore": "DHL",
      "note": "DDT per spedizione merci."
    }
  ],
  "fornitori": [
    {
      "id": "forn_casagrande",
      "nome": "Casagrande",
      "piva": "IT10000000001",
      "cf": "IT10000000001",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Casagrande",
      "email": "info@casagrande.it",
      "telefono": "+39 02 700000",
      "pec": "casagrande@pecdemo.it",
      "sdi": "SD00001",
      "indirizzo": "Via Demo 10, Milano",
      "sedeLegale": "Via Demo 10, Milano",
      "iban": "IT60X054281110100000000001",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Casagrande. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_ispa",
      "nome": "ISPA",
      "piva": "IT10000000002",
      "cf": "IT10000000002",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale ISPA",
      "email": "info@ispa.it",
      "telefono": "+39 02 700137",
      "pec": "ispa@pecdemo.it",
      "sdi": "SD00002",
      "indirizzo": "Via Demo 11, Milano",
      "sedeLegale": "Via Demo 11, Milano",
      "iban": "IT60X054281110100000000002",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: ISPA. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_entity",
      "nome": "Entity",
      "piva": "IT10000000003",
      "cf": "IT10000000003",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Entity",
      "email": "info@entity.it",
      "telefono": "+39 02 700274",
      "pec": "entity@pecdemo.it",
      "sdi": "SD00003",
      "indirizzo": "Via Demo 12, Milano",
      "sedeLegale": "Via Demo 12, Milano",
      "iban": "IT60X054281110100000000003",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Entity. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_gore",
      "nome": "Gore",
      "piva": "IT10000000004",
      "cf": "IT10000000004",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Gore",
      "email": "info@gore.it",
      "telefono": "+39 02 700411",
      "pec": "gore@pecdemo.it",
      "sdi": "SD00004",
      "indirizzo": "Via Demo 13, Milano",
      "sedeLegale": "Via Demo 13, Milano",
      "iban": "IT60X054281110100000000004",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Gore. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_mascherpa-cecchi",
      "nome": "Mascherpa / Cecchi",
      "piva": "IT10000000005",
      "cf": "IT10000000005",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Mascherpa / Cecchi",
      "email": "info@mascherpacecchi.it",
      "telefono": "+39 02 700548",
      "pec": "mascherpacecchi@pecdemo.it",
      "sdi": "SD00005",
      "indirizzo": "Via Demo 14, Milano",
      "sedeLegale": "Via Demo 14, Milano",
      "iban": "IT60X054281110100000000005",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: DOW CORNIG. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_emc-colosio",
      "nome": "EMC Colosio",
      "piva": "IT10000000006",
      "cf": "IT10000000006",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale EMC Colosio",
      "email": "info@emccolosio.it",
      "telefono": "+39 02 700685",
      "pec": "emccolosio@pecdemo.it",
      "sdi": "SD00006",
      "indirizzo": "Via Demo 15, Milano",
      "sedeLegale": "Via Demo 15, Milano",
      "iban": "IT60X054281110100000000006",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: vari. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_fornitore-da-definire",
      "nome": "Fornitore da definire",
      "piva": "IT10000000007",
      "cf": "IT10000000007",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Fornitore da definire",
      "email": "info@fornitoredadefinir.it",
      "telefono": "+39 02 700822",
      "pec": "fornitoredadefinire@pecdemo.it",
      "sdi": "SD00007",
      "indirizzo": "Via Demo 16, Milano",
      "sedeLegale": "Via Demo 16, Milano",
      "iban": "IT60X054281110100000000007",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Componenti senza fornitore esplicito nella BOM."
    },
    {
      "id": "forn_elektrozubehor",
      "nome": "Elektrozubehor",
      "piva": "IT10000000008",
      "cf": "IT10000000008",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Elektrozubehor",
      "email": "info@elektrozubehor.it",
      "telefono": "+39 02 700959",
      "pec": "elektrozubehor@pecdemo.it",
      "sdi": "SD00008",
      "indirizzo": "Via Demo 17, Milano",
      "sedeLegale": "Via Demo 17, Milano",
      "iban": "IT60X054281110100000000008",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Elektrozubehor. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_mef",
      "nome": "MEF",
      "piva": "IT10000000009",
      "cf": "IT10000000009",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale MEF",
      "email": "info@mef.it",
      "telefono": "+39 02 701096",
      "pec": "mef@pecdemo.it",
      "sdi": "SD00009",
      "indirizzo": "Via Demo 18, Milano",
      "sedeLegale": "Via Demo 18, Milano",
      "iban": "IT60X054281110100000000009",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Costruttore prevalente: Cembre. Sorgente: distinta base SIDEis ONE CC."
    },
    {
      "id": "forn_bossard",
      "nome": "Bossard",
      "piva": "IT10000000010",
      "cf": "IT10000000010",
      "categoria": "componenti",
      "statoQualifica": "approvato",
      "referente": "Ufficio commerciale Bossard",
      "email": "info@bossard.it",
      "telefono": "+39 02 701233",
      "pec": "bossard@pecdemo.it",
      "sdi": "SD00010",
      "indirizzo": "Via Demo 19, Milano",
      "sedeLegale": "Via Demo 19, Milano",
      "iban": "IT60X054281110100000000010",
      "leadTime": 14,
      "minimoOrdine": 100,
      "terminiPagamento": "bonifico_60",
      "note": "Fornitore minuterie e fissaggi emerso dalla distinta base."
    }
  ],
  "ordiniAcquisto": [
    {
      "id": "orda_sim_1",
      "numero": "OAC-2026001",
      "fornitore": "forn_fornitore-da-definire",
      "data": "2026-06-11",
      "stato": "ricevuto",
      "righe": [
        {
          "prodotto": "prod_auto-etichetta-prodotto-sx",
          "descrizione": "ETICHETTA PRODOTTO SX",
          "quantita": 42,
          "prezzoUnitario": 0.07,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 0.14,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 2.9400000000000004,
      "tasse": 0.6468,
      "totale": 3.5868,
      "preventivoOrigine": "preva_sim_1",
      "note": "Ordine inviato a fornitore."
    },
    {
      "id": "orda_sim_2",
      "numero": "OAC-2026002",
      "fornitore": "forn_mascherpa-cecchi",
      "data": "2026-04-20",
      "stato": "ricevuto",
      "righe": [
        {
          "prodotto": "prod_auto-scheda-led-std-12-led",
          "descrizione": "scheda led STD 12 LED",
          "quantita": 48,
          "prezzoUnitario": 5.5,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 11,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10009",
          "descrizione": "VASSOIO contenitore 8 PZ",
          "quantita": 1,
          "prezzoUnitario": 0.19,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 0.38,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10277",
          "descrizione": "VITE TRILOBATA M4 X 12 TORX A2",
          "quantita": 29,
          "prezzoUnitario": 0.08,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 0.16,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 266.4815,
      "tasse": 58.62593,
      "totale": 325.10742999999997,
      "preventivoOrigine": "preva_sim_2",
      "note": "Ordine inviato a fornitore."
    },
    {
      "id": "orda_sim_3",
      "numero": "OAC-2026003",
      "fornitore": "forn_mef",
      "data": "2026-05-13",
      "stato": "ricevuto",
      "righe": [
        {
          "prodotto": "prod_003-01-22",
          "descrizione": "DISSIPATORE SIDEIS",
          "quantita": 43,
          "prezzoUnitario": 2.32,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 4.64,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 99.75999999999999,
      "tasse": 21.9472,
      "totale": 121.70719999999999,
      "preventivoOrigine": "preva_sim_3",
      "note": "Ordine inviato a fornitore."
    }
  ],
  "ddtAcquisto": [
    {
      "id": "ddta_sim_1",
      "numero": "DDA-2026001",
      "fornitore": "forn_fornitore-da-definire",
      "data": "2026-06-16",
      "stato": "registrato",
      "righe": [
        {
          "prodotto": "prod_auto-etichetta-prodotto-sx",
          "descrizione": "ETICHETTA PRODOTTO SX",
          "quantita": 42,
          "prezzoUnitario": 0.07,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 0.14,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 2.9400000000000004,
      "tasse": 0.6468,
      "totale": 3.5868,
      "ordineOrigine": "orda_sim_1",
      "vettore": "Mittente",
      "note": "Ricezione merce."
    },
    {
      "id": "ddta_sim_2",
      "numero": "DDA-2026002",
      "fornitore": "forn_mascherpa-cecchi",
      "data": "2026-05-08",
      "stato": "registrato",
      "righe": [
        {
          "prodotto": "prod_auto-scheda-led-std-12-led",
          "descrizione": "scheda led STD 12 LED",
          "quantita": 48,
          "prezzoUnitario": 5.5,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 11,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10009",
          "descrizione": "VASSOIO contenitore 8 PZ",
          "quantita": 1,
          "prezzoUnitario": 0.19,
          "sconto1": 15,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "Finitura Standard",
          "costoConfezione": 0.38,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        },
        {
          "prodotto": "prod_10277",
          "descrizione": "VITE TRILOBATA M4 X 12 TORX A2",
          "quantita": 29,
          "prezzoUnitario": 0.08,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 0.16,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 266.4815,
      "tasse": 58.62593,
      "totale": 325.10742999999997,
      "ordineOrigine": "orda_sim_2",
      "vettore": "Mittente",
      "note": "Ricezione merce."
    },
    {
      "id": "ddta_sim_3",
      "numero": "DDA-2026003",
      "fornitore": "forn_mef",
      "data": "2026-05-18",
      "stato": "registrato",
      "righe": [
        {
          "prodotto": "prod_003-01-22",
          "descrizione": "DISSIPATORE SIDEIS",
          "quantita": 43,
          "prezzoUnitario": 2.32,
          "sconto1": 0,
          "sconto2": 0,
          "sconto3": 0,
          "linea": "Componenti",
          "descrizioneAggiuntiva": "",
          "costoConfezione": 4.64,
          "quantitaConfezione": 1,
          "tipologia": "componente",
          "iva": 22,
          "unitaMisura": "pz"
        }
      ],
      "imponibile": 99.75999999999999,
      "tasse": 21.9472,
      "totale": 121.70719999999999,
      "ordineOrigine": "orda_sim_3",
      "vettore": "Mittente",
      "note": "Ricezione merce."
    }
  ],
  "prodotti": [
    {
      "id": "prod_sideis_one_cc",
      "codice": "SIDEIS-ONE-CC",
      "alias": "SIDEis ONE CC",
      "nome": "Faretto SIDEis ONE CC",
      "tipo": "kit",
      "categoria": "Prodotti Finiti",
      "sottocategoria": "Faretto tecnico",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 24.46,
      "prezzoVendita": 62.37,
      "sku": "SIDEIS-ONE-CC",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 12,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "SIDEIS-ONE-CC",
      "peso": 0,
      "volume": 0,
      "produttore": "SIDEis",
      "descrizioneTecnica": "Distinta base importata dal foglio SIDEis ONE CC. Versione demo pronta per preventivi e ordini."
    },
    {
      "id": "prod_sideis_one_cv",
      "codice": "SIDEIS-ONE-CV",
      "alias": "SIDEis ONE CV",
      "nome": "Faretto SIDEis ONE CV",
      "tipo": "kit",
      "categoria": "Prodotti Finiti",
      "sottocategoria": "Faretto tecnico",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 31.3,
      "prezzoVendita": 79.82,
      "sku": "SIDEIS-ONE-CV",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 9,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "SIDEIS-ONE-CV",
      "peso": 0,
      "volume": 0,
      "produttore": "SIDEis",
      "descrizioneTecnica": "Distinta base importata dal foglio SIDEis ONE CV. Versione demo pronta per preventivi e ordini."
    },
    {
      "id": "prod_001-05-23",
      "codice": "001.05.23",
      "alias": "001.05.23",
      "nome": "LENTE ASIMMETRICA SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 4.52,
      "prezzoVendita": 9.49,
      "sku": "001.05.23",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Casagrande",
      "descrizioneTecnica": "LENTE SIDEis S3 nuova 5' neutra senza cornice | NEUTRA | Approvvigionato da: SIDEis conto lavoro"
    },
    {
      "id": "prod_10031",
      "codice": "10031",
      "alias": "10031",
      "nome": "LENTE ASIMMETRICA SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 2.5,
      "prezzoVendita": 5.25,
      "sku": "10031",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Casagrande",
      "descrizioneTecnica": "LENTE SIDEis S3 nuova 5' cornice tampografata | TAMPOGRAFATA | Approvvigionato da: SIDEis conto lavoro"
    },
    {
      "id": "prod_002-01-22",
      "codice": "002.01.22",
      "alias": "002.01.22",
      "nome": "SCOCCA BASE SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 3.76,
      "prezzoVendita": 7.9,
      "sku": "002.01.22",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "ISPA",
      "descrizioneTecnica": "Componente meccanico da distinta base SIDEis ONE."
    },
    {
      "id": "prod_003-01-22",
      "codice": "003.01.22",
      "alias": "003.01.22",
      "nome": "DISSIPATORE SIDEIS",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 2.32,
      "prezzoVendita": 4.87,
      "sku": "003.01.22",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "ISPA",
      "descrizioneTecnica": "Dissipatore meccanico da distinta base SIDEis ONE."
    },
    {
      "id": "prod_auto-scheda-led-std-12-led",
      "codice": "AUTO_SCHEDA_LED_STD_12_LED",
      "alias": "xxxxx",
      "nome": "scheda led STD 12 LED",
      "tipo": "semplice",
      "categoria": "Elettronica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 5.5,
      "prezzoVendita": 12.93,
      "sku": "AUTO_SCHEDA_LED_STD_12_LED",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Entity",
      "descrizioneTecnica": "Scheda LED generica. Il codice in BOM era da definire."
    },
    {
      "id": "prod_10217",
      "codice": "10217",
      "alias": "10217",
      "nome": "scheda driver interna std",
      "tipo": "semplice",
      "categoria": "Elettronica",
      "sottocategoria": "CV",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 6.84,
      "prezzoVendita": 16.07,
      "sku": "10217",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Entity",
      "descrizioneTecnica": "Driver interno standard per versione CV."
    },
    {
      "id": "prod_027-01-20",
      "codice": "027.01.20",
      "alias": "027.01.20",
      "nome": "VALVOLA DI SFIATO (POLY VENT XS PMF200125)",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 1.8,
      "prezzoVendita": 3.78,
      "sku": "027.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "PMF200125",
      "peso": 0,
      "volume": 0,
      "produttore": "Gore",
      "descrizioneTecnica": "Valvola di sfiato Poly Vent XS PMF200125."
    },
    {
      "id": "prod_10248",
      "codice": "10248",
      "alias": "10248",
      "nome": "SILICONE",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.23,
      "prezzoVendita": 0.48,
      "sku": "10248",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "7091",
      "peso": 0,
      "volume": 0,
      "produttore": "DOW CORNIG",
      "descrizioneTecnica": "Dose di silicone per singolo prodotto."
    },
    {
      "id": "prod_10250",
      "codice": "10250",
      "alias": "10250",
      "nome": "PASTA TERMOCONDUTTIVA",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.05,
      "prezzoVendita": 0.2,
      "sku": "10250",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "HTC",
      "peso": 0,
      "volume": 0,
      "produttore": "ELECTROLUBE",
      "descrizioneTecnica": "Dose di pasta termoconduttiva per singolo prodotto."
    },
    {
      "id": "prod_032-01-20",
      "codice": "032.01.20",
      "alias": "032.01.20",
      "nome": "CAVO H05RN-F 2x0,75",
      "tipo": "semplice",
      "categoria": "Cablaggio",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.78,
      "prezzoVendita": 1.83,
      "sku": "032.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "vari",
      "descrizioneTecnica": "Spezzone da 1,5 m come da distinta base."
    },
    {
      "id": "prod_033-01-20",
      "codice": "033.01.20",
      "alias": "033.01.20",
      "nome": "O-RING X VITI CHIUSURA",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.02,
      "prezzoVendita": 0.17,
      "sku": "033.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 240,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Minuteria di chiusura con qty 6 per prodotto."
    },
    {
      "id": "prod_10036",
      "codice": "10036",
      "alias": "10036",
      "nome": "passacavo M12x1,5",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.15,
      "prezzoVendita": 0.32,
      "sku": "10036",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "131390",
      "peso": 0,
      "volume": 0,
      "produttore": "Elektrozubehor",
      "descrizioneTecnica": "Alternativa al pressacavo a seconda del codice prodotto."
    },
    {
      "id": "prod_024-01-20",
      "codice": "024.01.20",
      "alias": "024.01.20",
      "nome": "pressacavo",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 1.54,
      "prezzoVendita": 3.23,
      "sku": "024.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "2900_M12N",
      "peso": 0,
      "volume": 0,
      "produttore": "Cembre",
      "descrizioneTecnica": "Alternativa al passacavo a seconda del codice prodotto."
    },
    {
      "id": "prod_025-01-20",
      "codice": "025.01.20",
      "alias": "025.01.20",
      "nome": "dado pressacavo",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.19,
      "prezzoVendita": 0.4,
      "sku": "025.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Cembre",
      "descrizioneTecnica": "Accessorio del pressacavo da distinta base."
    },
    {
      "id": "prod_012-01-20",
      "codice": "012.01.20",
      "alias": "012.01.20",
      "nome": "VITE TRILOBATA M3 X 10 TORX A2 TESTA SVASATA",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.05,
      "prezzoVendita": 0.2,
      "sku": "012.01.20",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Minuteria da terzista per assemblaggio."
    },
    {
      "id": "prod_10017",
      "codice": "10017",
      "alias": "10017",
      "nome": "RONDELLA distanziale isolante 4,2x8 H5",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.05,
      "prezzoVendita": 0.2,
      "sku": "10017",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 80,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Rondella isolante con qty 2 per prodotto."
    },
    {
      "id": "prod_10014",
      "codice": "10014",
      "alias": "10014",
      "nome": "VITE TRILOBATA M4 X 10 TORX A2",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.03,
      "prezzoVendita": 0.18,
      "sku": "10014",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 240,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Vite trilobata M4x10 con qty 6 per prodotto."
    },
    {
      "id": "prod_10277",
      "codice": "10277",
      "alias": "10277",
      "nome": "VITE TRILOBATA M4 X 12 TORX A2",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.08,
      "prezzoVendita": 0.23,
      "sku": "10277",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 80,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Vite trilobata M4x12 con qty 2 per prodotto."
    },
    {
      "id": "prod_10274",
      "codice": "10274",
      "alias": "10274",
      "nome": "DADO FLANGIATO M6 A2",
      "tipo": "semplice",
      "categoria": "Meccanica",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.06,
      "prezzoVendita": 0.21,
      "sku": "10274",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 80,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Bossard",
      "descrizioneTecnica": "Dado flangiato M6 A2 con qty 2 per prodotto."
    },
    {
      "id": "prod_10278",
      "codice": "10278",
      "alias": "10278",
      "nome": "IMBALLO",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.07,
      "prezzoVendita": 0.22,
      "sku": "10278",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Quota imballo riferita al singolo prodotto."
    },
    {
      "id": "prod_10009",
      "codice": "10009",
      "alias": "10009",
      "nome": "VASSOIO contenitore 8 PZ",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.19,
      "prezzoVendita": 0.4,
      "sku": "10009",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Vassoio contenitore con quota unitaria per singolo prodotto."
    },
    {
      "id": "prod_auto-etichetta-prodotto-sx",
      "codice": "AUTO_ETICHETTA_PRODOTTO_SX",
      "alias": "",
      "nome": "ETICHETTA PRODOTTO SX",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.07,
      "prezzoVendita": 0.22,
      "sku": "AUTO_ETICHETTA_PRODOTTO_SX",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Etichetta prodotto per demo SIDEis ONE."
    },
    {
      "id": "prod_auto-etichetta-marchi-dx",
      "codice": "AUTO_ETICHETTA_MARCHI_DX",
      "alias": "",
      "nome": "ETICHETTA MARCHI DX",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.07,
      "prezzoVendita": 0.22,
      "sku": "AUTO_ETICHETTA_MARCHI_DX",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Etichetta marchi lato destro per demo SIDEis ONE."
    },
    {
      "id": "prod_auto-etichetta-bandiera-cavo",
      "codice": "AUTO_ETICHETTA_BANDIERA_CAVO",
      "alias": "",
      "nome": "ETICHETTA BANDIERA CAVO",
      "tipo": "semplice",
      "categoria": "Imballo",
      "sottocategoria": "CC",
      "gruppo": "SIDEis ONE",
      "iva": "22",
      "prezzoAcquisto": 0.14,
      "prezzoVendita": 0.29,
      "sku": "AUTO_ETICHETTA_BANDIERA_CAVO",
      "unitaMisura": "pz",
      "quantitaConfezione": 1,
      "quantitaEsistente": 40,
      "brand": "SIDEis",
      "provvigione": 0,
      "barcode": "",
      "metel": "",
      "magazzino": "si",
      "codDocumento": "",
      "peso": 0,
      "volume": 0,
      "produttore": "Fornitore da definire",
      "descrizioneTecnica": "Etichetta bandiera cavo per demo SIDEis ONE."
    }
  ],
  "distintaBase": [
    {
      "id": "bom_1",
      "prodotto": "prod_sideis_one_cc",
      "componentiCsv": "001.05.23:1, 10031:1, 002.01.22:1, 003.01.22:1, AUTO_SCHEDA_LED_STD_12_LED:1, 027.01.20:1, 10248:1, 10250:1, 032.01.20:1, 033.01.20:6, 024.01.20:1, 025.01.20:1, 012.01.20:1, 10017:2, 10014:6, 10277:2, 10274:2, 10278:1, 10009:1, AUTO_ETICHETTA_PRODOTTO_SX:1, AUTO_ETICHETTA_MARCHI_DX:1, AUTO_ETICHETTA_BANDIERA_CAVO:1"
    },
    {
      "id": "bom_2",
      "prodotto": "prod_sideis_one_cv",
      "componentiCsv": "001.05.23:1, 10031:1, 002.01.22:1, 003.01.22:1, AUTO_SCHEDA_LED_STD_12_LED:1, 10217:1, 027.01.20:1, 10248:1, 10250:1, 032.01.20:1, 033.01.20:6, 024.01.20:1, 025.01.20:1, 012.01.20:1, 10017:2, 10014:6, 10277:2, 10274:2, 10278:1, 10009:1, AUTO_ETICHETTA_PRODOTTO_SX:1, AUTO_ETICHETTA_MARCHI_DX:1, AUTO_ETICHETTA_BANDIERA_CAVO:1"
    }
  ],
  "magazzino": [
    {
      "id": "mag_1",
      "prodotto": "prod_sideis_one_cc",
      "quantita": 12,
      "quantitaMinima": 4,
      "valoreFIFO": 293.52,
      "ubicazione": "ASSEMBLAGGIO-01"
    },
    {
      "id": "mag_2",
      "prodotto": "prod_sideis_one_cv",
      "quantita": 9,
      "quantitaMinima": 4,
      "valoreFIFO": 281.7,
      "ubicazione": "ASSEMBLAGGIO-02"
    },
    {
      "id": "mag_3",
      "prodotto": "prod_001-05-23",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 180.8,
      "ubicazione": "COMP-03"
    },
    {
      "id": "mag_4",
      "prodotto": "prod_10031",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 100,
      "ubicazione": "COMP-04"
    },
    {
      "id": "mag_5",
      "prodotto": "prod_002-01-22",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 150.4,
      "ubicazione": "COMP-05"
    },
    {
      "id": "mag_6",
      "prodotto": "prod_003-01-22",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 92.8,
      "ubicazione": "COMP-06"
    },
    {
      "id": "mag_7",
      "prodotto": "prod_auto-scheda-led-std-12-led",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 220,
      "ubicazione": "COMP-07"
    },
    {
      "id": "mag_8",
      "prodotto": "prod_10217",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 273.6,
      "ubicazione": "COMP-08"
    },
    {
      "id": "mag_9",
      "prodotto": "prod_027-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 72,
      "ubicazione": "COMP-09"
    },
    {
      "id": "mag_10",
      "prodotto": "prod_10248",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 9.2,
      "ubicazione": "COMP-10"
    },
    {
      "id": "mag_11",
      "prodotto": "prod_10250",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2,
      "ubicazione": "COMP-11"
    },
    {
      "id": "mag_12",
      "prodotto": "prod_032-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 31.2,
      "ubicazione": "COMP-12"
    },
    {
      "id": "mag_13",
      "prodotto": "prod_033-01-20",
      "quantita": 240,
      "quantitaMinima": 20,
      "valoreFIFO": 4.8,
      "ubicazione": "COMP-13"
    },
    {
      "id": "mag_14",
      "prodotto": "prod_10036",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 6,
      "ubicazione": "COMP-14"
    },
    {
      "id": "mag_15",
      "prodotto": "prod_024-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 61.6,
      "ubicazione": "COMP-15"
    },
    {
      "id": "mag_16",
      "prodotto": "prod_025-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 7.6,
      "ubicazione": "COMP-16"
    },
    {
      "id": "mag_17",
      "prodotto": "prod_012-01-20",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2,
      "ubicazione": "COMP-17"
    },
    {
      "id": "mag_18",
      "prodotto": "prod_10017",
      "quantita": 80,
      "quantitaMinima": 20,
      "valoreFIFO": 4,
      "ubicazione": "COMP-18"
    },
    {
      "id": "mag_19",
      "prodotto": "prod_10014",
      "quantita": 240,
      "quantitaMinima": 20,
      "valoreFIFO": 7.2,
      "ubicazione": "COMP-19"
    },
    {
      "id": "mag_20",
      "prodotto": "prod_10277",
      "quantita": 80,
      "quantitaMinima": 20,
      "valoreFIFO": 6.4,
      "ubicazione": "COMP-20"
    },
    {
      "id": "mag_21",
      "prodotto": "prod_10274",
      "quantita": 80,
      "quantitaMinima": 20,
      "valoreFIFO": 4.8,
      "ubicazione": "COMP-21"
    },
    {
      "id": "mag_22",
      "prodotto": "prod_10278",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2.8,
      "ubicazione": "COMP-22"
    },
    {
      "id": "mag_23",
      "prodotto": "prod_10009",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 7.6,
      "ubicazione": "COMP-23"
    },
    {
      "id": "mag_24",
      "prodotto": "prod_auto-etichetta-prodotto-sx",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2.8,
      "ubicazione": "COMP-24"
    },
    {
      "id": "mag_25",
      "prodotto": "prod_auto-etichetta-marchi-dx",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 2.8,
      "ubicazione": "COMP-25"
    },
    {
      "id": "mag_26",
      "prodotto": "prod_auto-etichetta-bandiera-cavo",
      "quantita": 40,
      "quantitaMinima": 10,
      "valoreFIFO": 5.6,
      "ubicazione": "COMP-26"
    }
  ]
};